<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns="http://www.opengis.net/citygml/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:fme="http://www.safe.com/xml/xmltables">
  <gml:name>interior-LOD1</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="9fd16237-61d1-494c-b265-4e51b42046ed">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1969</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="191d41ed-41ec-48ba-89e4-2c45a9d87aad">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6f32722d-a845-4bd5-8f5b-2cb72fb2ab65">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>3.1399999999999997 0.2 0.115 3.1399999999999997 7.569999999999999 0.115 3.1399999999999997 7.569999999999999 17.335000000000004 3.1399999999999997 0.2 17.335000000000004 3.1399999999999997 0.2 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="133ff8db-f296-4c5c-9c41-713ade65fdab">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.2 0.2 0.115 0.2 7.569999999999999 0.115 3.1399999999999997 7.569999999999999 0.115 3.1399999999999997 0.2 0.115 0.2 0.2 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5590d2c4-b3bf-4d78-97ab-75e3c33be876">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.2 0.2 0.115 3.1399999999999997 0.2 0.115 3.1399999999999997 0.2 17.335000000000004 0.2 0.2 17.335000000000004 0.2 0.2 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6440952f-094f-45d0-8b0e-806443320cbf">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>3.1399999999999997 7.569999999999999 0.115 0.2 7.569999999999999 0.115 0.2 7.569999999999999 17.335000000000004 3.1399999999999997 7.569999999999999 17.335000000000004 3.1399999999999997 7.569999999999999 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b9b50e93-7f09-4c27-b94e-7f9c98aabab0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.2 7.569999999999999 0.115 0.2 0.2 0.115 0.2 0.2 17.335000000000004 0.2 7.569999999999999 17.335000000000004 0.2 7.569999999999999 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="27a60f10-43f3-409d-b331-5af925c680ca">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.2 0.2 17.335000000000004 3.1399999999999997 0.2 17.335000000000004 3.1399999999999997 7.569999999999999 17.335000000000004 0.2 7.569999999999999 17.335000000000004 0.2 0.2 17.335000000000004</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6e58349d-cbc4-4c44-95e6-5e550d5d0899">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="8b525e2b-f588-4f3e-a9f7-9d14232506b9">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9715d131-28de-4934-bbe8-a873118783e1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>5.3999999999999995 20.32 0.125 5.3999999999999995 29.28 0.125 5.3999999999999995 29.28 3.395 5.3999999999999995 20.32 3.395 5.3999999999999995 20.32 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a1d47116-847a-4f05-97c3-e08f5cd78696">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.32 20.32 0.125 0.32 29.28 0.125 5.3999999999999995 29.28 0.125 5.3999999999999995 20.32 0.125 0.32 20.32 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="23c77d6e-94bc-4c7d-8153-139109a7ca0c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.32 20.32 0.125 5.3999999999999995 20.32 0.125 5.3999999999999995 20.32 3.395 0.32 20.32 3.395 0.32 20.32 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a3d18e1b-c65c-46da-80fb-788d34a18869">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>5.3999999999999995 29.28 0.125 0.32 29.28 0.125 0.32 29.28 3.395 5.3999999999999995 29.28 3.395 5.3999999999999995 29.28 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0389aaed-1f6a-4864-91fd-29ff2ddca6e1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.32 29.28 0.125 0.32 20.32 0.125 0.32 20.32 3.395 0.32 29.28 3.395 0.32 29.28 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="17d41df6-4230-417b-a95c-bf7f819e2826">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.32 20.32 3.395 0.32 29.28 3.395 5.3999999999999995 29.28 3.395 5.3999999999999995 20.32 3.395 0.32 20.32 3.395</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c6b69366-18bd-4020-aaa6-aa5b5d67082d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.32 20.32 6.038356643356643 5.3999999999999995 20.32 3.395 5.3999999999999995 29.28 3.395 0.32 29.28 6.038356643356643 0.32 20.32 6.038356643356643</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4bdc9803-1359-4d34-aae3-03caf381f4dc">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.32 20.32 3.395 5.3999999999999995 20.32 3.395 0.32 20.32 6.038356643356643 0.32 20.32 3.395</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="42a53783-242b-4bf3-ba52-146d11667518">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>5.3999999999999995 29.28 3.395 0.32 29.28 3.395 0.32 29.28 6.038356643356643 5.3999999999999995 29.28 3.395</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d012a382-c084-46b1-b3de-7a06311a305c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.32 20.32 3.395 0.32 20.32 6.038356643356643 0.32 29.28 6.038356643356643 0.32 29.28 3.395 0.32 20.32 3.395</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f9d58a7b-a73d-4aea-a1de-f635941ce646">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.32 20.32 3.395 5.3999999999999995 20.32 3.395 0.32 20.32 6.038356643356643 0.32 20.32 3.395</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0152ea5b-1bd1-402f-9e3c-22c0d273455b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>5.3999999999999995 29.28 3.395 0.32 29.28 3.395 0.32 29.28 6.038356643356643 5.3999999999999995 29.28 3.395</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="89dbec75-b1ed-4053-a01b-c30920f34683">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.32 20.32 3.395 0.32 20.32 6.038356643356643 0.32 29.28 6.038356643356643 0.32 29.28 3.395 0.32 20.32 3.395</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="92a9ffcc-a809-436b-ab8f-213341025556">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1965</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="439b8f42-559c-48eb-a2de-e809104af1eb">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fce493c5-2d97-4200-9ad6-522a5e5fd1ad">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>7.18 40.2 0.135 7.18 42.839999999999996 0.135 7.18 42.839999999999996 15.965000000000002 7.18 40.2 15.965000000000002 7.18 40.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a57b21b8-12d9-4bf9-ac2d-29e5fb7296d9">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.2 40.2 0.135 0.2 42.839999999999996 0.135 7.18 42.839999999999996 0.135 7.18 40.2 0.135 0.2 40.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6ce3713d-9f29-440e-8c2a-d55295a522ae">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.2 40.2 0.135 7.18 40.2 0.135 7.18 40.2 15.965000000000002 0.2 40.2 15.965000000000002 0.2 40.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="eb738312-4a93-4eda-9321-45becd31aeb4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>7.18 42.839999999999996 0.135 0.2 42.839999999999996 0.135 0.2 42.839999999999996 15.965000000000002 7.18 42.839999999999996 15.965000000000002 7.18 42.839999999999996 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1a78029a-415f-4249-a4eb-1f169c2179a0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.2 42.839999999999996 0.135 0.2 40.2 0.135 0.2 40.2 15.965000000000002 0.2 42.839999999999996 15.965000000000002 0.2 42.839999999999996 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="532415d5-2dd3-4ec4-b4f4-2223f5ed4814">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.2 40.2 15.965000000000002 7.18 40.2 15.965000000000002 7.18 42.839999999999996 15.965000000000002 0.2 42.839999999999996 15.965000000000002 0.2 40.2 15.965000000000002</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="580bc1f5-b498-4048-a45b-e65a9d18c75a">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1990</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="dc4492d7-9b64-4c58-b57e-fa0fd6e1d469">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3f47cf2e-46bd-44a7-be4b-ddba1930b6c0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>8.99 60.28 0.135 8.99 63.089999999999996 0.135 8.99 63.089999999999996 6.3149999999999995 8.99 60.28 6.3149999999999995 8.99 60.28 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="47a066c7-fe37-4ada-8421-cc2c55c2b99a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.28 60.28 0.135 0.28 63.089999999999996 0.135 8.99 63.089999999999996 0.135 8.99 60.28 0.135 0.28 60.28 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a87b2168-0d01-4de1-9b6d-fbc4bf978c24">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.28 60.28 0.135 8.99 60.28 0.135 8.99 60.28 6.3149999999999995 0.28 60.28 6.3149999999999995 0.28 60.28 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d9ee9190-5d9e-493b-87c5-3a01392bbdc0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>8.99 63.089999999999996 0.135 0.28 63.089999999999996 0.135 0.28 63.089999999999996 6.3149999999999995 8.99 63.089999999999996 6.3149999999999995 8.99 63.089999999999996 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="676ba1ca-c4c2-4ce3-9bad-a3f3b23b968c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.28 63.089999999999996 0.135 0.28 60.28 0.135 0.28 60.28 6.3149999999999995 0.28 63.089999999999996 6.3149999999999995 0.28 63.089999999999996 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="75e4cecc-7991-4d2b-9a1a-704b856d1810">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.28 60.28 6.3149999999999995 0.28 63.089999999999996 6.3149999999999995 8.99 63.089999999999996 6.3149999999999995 8.99 60.28 6.3149999999999995 0.28 60.28 6.3149999999999995</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="61fcb611-f280-4ec3-bec7-6338c2777e9f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.28 60.28 8.720091693635384 8.99 60.28 6.3149999999999995 8.99 63.089999999999996 6.3149999999999995 0.28 63.089999999999996 8.720091693635384 0.28 60.28 8.720091693635384</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fbdc6a21-2699-40d4-a4f0-e73794701466">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.28 60.28 6.3149999999999995 8.99 60.28 6.3149999999999995 0.28 60.28 8.720091693635384 0.28 60.28 6.3149999999999995</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="dfdbeb7b-72c5-4848-ba04-cbf8601f4593">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>8.99 63.089999999999996 6.3149999999999995 0.28 63.089999999999996 6.3149999999999995 0.28 63.089999999999996 8.720091693635384 8.99 63.089999999999996 6.3149999999999995</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b6f4308f-bacf-4ad2-8b09-813760c32244">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.28 60.28 6.3149999999999995 0.28 60.28 8.720091693635384 0.28 63.089999999999996 8.720091693635384 0.28 63.089999999999996 6.3149999999999995 0.28 60.28 6.3149999999999995</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ae264503-5d56-4460-a665-ec26c616e396">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.28 60.28 6.3149999999999995 8.99 60.28 6.3149999999999995 0.28 60.28 8.720091693635384 0.28 60.28 6.3149999999999995</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e977f806-ed1b-464f-be17-b8770251be31">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>8.99 63.089999999999996 6.3149999999999995 0.28 63.089999999999996 6.3149999999999995 0.28 63.089999999999996 8.720091693635384 8.99 63.089999999999996 6.3149999999999995</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="517317bb-4a9e-4e23-aba3-c8e2d550cde8">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.28 60.28 6.3149999999999995 0.28 60.28 8.720091693635384 0.28 63.089999999999996 8.720091693635384 0.28 63.089999999999996 6.3149999999999995 0.28 60.28 6.3149999999999995</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="95a4abfb-cd95-422f-9c27-ebea911dcc4f">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1967</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="ea4d9237-ec8c-40b5-8102-e23b71f5c586">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7e6ef412-b235-49f2-b6d5-197cdc6cec95">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.790000000000003 0.2 0.1 23.790000000000003 5.54 0.1 23.790000000000003 5.54 9.43 23.790000000000003 0.2 9.43 23.790000000000003 0.2 0.1</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="172d1873-8e73-429b-b2cf-4c8f508bb2a1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 0.2 0.1 20.2 5.54 0.1 23.790000000000003 5.54 0.1 23.790000000000003 0.2 0.1 20.2 0.2 0.1</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="dc731034-16bf-4efa-b23a-4e5f2f93a54c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 0.2 0.1 23.790000000000003 0.2 0.1 23.790000000000003 0.2 9.43 20.2 0.2 9.43 20.2 0.2 0.1</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="235a47dc-3cde-4a94-a133-2f1d2bdd73b1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.790000000000003 5.54 0.1 20.2 5.54 0.1 20.2 5.54 9.43 23.790000000000003 5.54 9.43 23.790000000000003 5.54 0.1</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f542fb8e-0fc0-4bc5-84ab-c0ccc34b4931">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 5.54 0.1 20.2 0.2 0.1 20.2 0.2 9.43 20.2 5.54 9.43 20.2 5.54 0.1</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="060f7cf8-1466-42a4-bcfa-26ab7866e613">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 0.2 9.43 23.790000000000003 0.2 9.43 21.995 2.29 11.274486215538847 20.2 0.2 9.43</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="370f8b4a-28c3-4a17-abe0-a0a0d8b836c1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.790000000000003 0.2 9.43 23.790000000000003 5.54 9.43 21.995 3.45 11.274486215538847 21.995 2.29 11.274486215538847 23.790000000000003 0.2 9.43</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f0888dc5-3e34-4d32-9c60-1ae52bebfd20">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.790000000000003 5.54 9.43 20.2 5.54 9.43 21.995 3.45 11.274486215538847 23.790000000000003 5.54 9.43</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="dbdf7b04-3884-4525-9fa2-36fb59d5604f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 5.54 9.43 20.2 0.2 9.43 21.995 2.29 11.274486215538847 21.995 3.45 11.274486215538847 20.2 5.54 9.43</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="3d5dea93-0b71-41ff-b5f5-438bad25f186">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1959</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="6f3c4492-a417-438a-9a16-1fe915794cf6">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b2878a92-dc0d-405b-8621-b64e16380af1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>22.91 20.2 0.135 22.91 28.63 0.135 22.91 28.63 9.525 22.91 20.2 9.525 22.91 20.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d0aa630d-ef0d-4baf-bd3c-38ff6cdeab64">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 20.2 0.135 20.2 28.63 0.135 22.91 28.63 0.135 22.91 20.2 0.135 20.2 20.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5ba1ae0e-f7d3-440c-adcc-1dde49090458">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 20.2 0.135 22.91 20.2 0.135 22.91 20.2 9.525 20.2 20.2 9.525 20.2 20.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="98b54518-b029-46d0-ba39-47678ead23f5">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>22.91 28.63 0.135 20.2 28.63 0.135 20.2 28.63 9.525 22.91 28.63 9.525 22.91 28.63 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="986e9f7f-7b1a-4763-be48-4ee97d6bb311">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 28.63 0.135 20.2 20.2 0.135 20.2 20.2 9.525 20.2 28.63 9.525 20.2 28.63 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d7c79ba1-5ad6-4e37-a8d0-2f43a91f63d2">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 20.2 9.525 22.91 20.2 9.525 21.555 21.77 11.555321543408361 20.2 20.2 9.525</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="af7c79d4-63ea-46d9-9d56-fbfa0d14f9a4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>22.91 20.2 9.525 22.91 28.63 9.525 21.555 27.06 11.555321543408361 21.555 21.77 11.555321543408361 22.91 20.2 9.525</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="248a3e6f-0ee1-47cb-8e5e-c368c2eff969">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>22.91 28.63 9.525 20.2 28.63 9.525 21.555 27.06 11.555321543408361 22.91 28.63 9.525</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c9244a6f-c242-4f9d-a23b-540001792ac0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 28.63 9.525 20.2 20.2 9.525 21.555 21.77 11.555321543408361 21.555 27.06 11.555321543408361 20.2 28.63 9.525</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="60bc0619-7b36-44bd-ae91-da3c4563c587">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1948</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="ffc76d56-e85d-45f6-be22-e1735b684d58">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5ccd7071-c26b-4554-aed5-5faa18c97cda">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>22.96 40.2 0.135 22.96 48.53 0.135 22.96 48.53 10.034999999999998 22.96 40.2 10.034999999999998 22.96 40.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="872f4e38-b2ab-4fdc-9cfd-5804d2ec8c72">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 40.2 0.135 20.2 48.53 0.135 22.96 48.53 0.135 22.96 40.2 0.135 20.2 40.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b41bbbce-ad5e-42fe-8dbc-9a101d323134">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 40.2 0.135 22.96 40.2 0.135 22.96 40.2 10.034999999999998 20.2 40.2 10.034999999999998 20.2 40.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b7228517-9193-45ea-ae8a-4f271b52548a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>22.96 48.53 0.135 20.2 48.53 0.135 20.2 48.53 10.034999999999998 22.96 48.53 10.034999999999998 22.96 48.53 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3dd83c2e-a7ba-4ee2-b44a-360edd64b21c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 48.53 0.135 20.2 40.2 0.135 20.2 40.2 10.034999999999998 20.2 48.53 10.034999999999998 20.2 48.53 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9a69e4c7-01e4-4aee-ba07-9af741f11a48">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 40.2 10.034999999999998 20.2 48.53 10.034999999999998 22.96 48.53 10.034999999999998 22.96 40.2 10.034999999999998 20.2 40.2 10.034999999999998</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a2dfef8e-f983-4a76-bbac-cd16b71a90e7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 40.2 11.945886075949367 22.96 40.2 10.034999999999998 22.96 48.53 10.034999999999998 20.2 48.53 11.945886075949367 20.2 40.2 11.945886075949367</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="94173661-2d78-41b9-9d6b-1df49668dfec">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 40.2 10.034999999999998 22.96 40.2 10.034999999999998 20.2 40.2 11.945886075949367 20.2 40.2 10.034999999999998</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b443c8ab-e4a9-4649-b344-a322145a519b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>22.96 48.53 10.034999999999998 20.2 48.53 10.034999999999998 20.2 48.53 11.945886075949367 22.96 48.53 10.034999999999998</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1b0ec43f-a6b7-4aef-8153-dc9ed4e01f02">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 40.2 10.034999999999998 20.2 40.2 11.945886075949367 20.2 48.53 11.945886075949367 20.2 48.53 10.034999999999998 20.2 40.2 10.034999999999998</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9dc3b29e-21ce-443f-a9b3-b3392aaca904">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 40.2 10.034999999999998 22.96 40.2 10.034999999999998 20.2 40.2 11.945886075949367 20.2 40.2 10.034999999999998</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="835db77c-9d3f-4e26-8ea8-af40031bec8f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>22.96 48.53 10.034999999999998 20.2 48.53 10.034999999999998 20.2 48.53 11.945886075949367 22.96 48.53 10.034999999999998</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d2838731-5bcc-475a-95ae-a2daf103c219">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 40.2 10.034999999999998 20.2 40.2 11.945886075949367 20.2 48.53 11.945886075949367 20.2 48.53 10.034999999999998 20.2 40.2 10.034999999999998</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="d333dfad-c0a0-4cad-8565-a93c5e17ce8d">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>2009</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="1d5f0e57-eb89-4e06-8ece-0981e745af5f">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1d002275-58a4-4208-b74d-a6c5258f1382">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>28.16 60.2 0.13 28.16 63.92 0.13 28.16 63.92 6.67 28.16 60.2 6.67 28.16 60.2 0.13</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="137323e3-5920-4ac8-a3fd-0de1d3fae978">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 60.2 0.13 20.2 63.92 0.13 28.16 63.92 0.13 28.16 60.2 0.13 20.2 60.2 0.13</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3ddae18a-7fa1-4be4-8fc3-3e373539c52e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 60.2 0.13 28.16 60.2 0.13 28.16 60.2 6.67 20.2 60.2 6.67 20.2 60.2 0.13</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="cbd36bd8-3c97-43d9-ad06-4cbe75a12d9e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>28.16 63.92 0.13 20.2 63.92 0.13 20.2 63.92 6.67 28.16 63.92 6.67 28.16 63.92 0.13</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="27e22343-6a13-4350-a58f-01ae1782250a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 63.92 0.13 20.2 60.2 0.13 20.2 60.2 6.67 20.2 63.92 6.67 20.2 63.92 0.13</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6d779174-61ec-4329-8124-bc33053738a8">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.2 60.2 6.67 28.16 60.2 6.67 28.16 63.92 6.67 20.2 63.92 6.67 20.2 60.2 6.67</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="fcbb6855-ac3c-4a96-97b2-4a33bbfeede9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="71a57024-3d0e-4272-8663-ca5878ae3a0b">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="50ac79ce-d6e3-435c-b146-e9bdf6ebda42">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>45.8 0.28 0.145 45.8 7.069999999999999 0.145 45.8 7.069999999999999 10.225 45.8 0.28 10.225 45.8 0.28 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="181c21f6-dcf8-423a-95c9-9ac875fe4770">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.28 0.28 0.145 40.28 7.069999999999999 0.145 45.8 7.069999999999999 0.145 45.8 0.28 0.145 40.28 0.28 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="145ec935-a446-45b1-a6a7-6b4626f58a0e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.28 0.28 0.145 45.8 0.28 0.145 45.8 0.28 10.225 40.28 0.28 10.225 40.28 0.28 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3082f460-34fd-4a98-a7dd-1eceeec0fc43">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>45.8 7.069999999999999 0.145 40.28 7.069999999999999 0.145 40.28 7.069999999999999 10.225 45.8 7.069999999999999 10.225 45.8 7.069999999999999 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3800ad2c-8ac9-4fa4-a4df-6bb22c3d4b0f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.28 7.069999999999999 0.145 40.28 0.28 0.145 40.28 0.28 10.225 40.28 7.069999999999999 10.225 40.28 7.069999999999999 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="db0b154b-9942-4c85-927c-f5b82150238a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.28 0.28 10.225 45.8 0.28 10.225 43.04 0.28 13.438947368421053 40.28 0.28 10.225</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="95d0bb10-d579-4f55-990d-f4c86208c615">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>45.8 0.28 10.225 45.8 7.069999999999999 10.225 43.04 7.069999999999999 13.438947368421053 43.04 0.28 13.438947368421053 45.8 0.28 10.225</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="300e494b-4c83-402d-9c0b-daad1a5bd651">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>45.8 7.069999999999999 10.225 40.28 7.069999999999999 10.225 43.04 7.069999999999999 13.438947368421053 45.8 7.069999999999999 10.225</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b29c2a12-5898-4b23-a999-cdc8a4889254">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.28 7.069999999999999 10.225 40.28 0.28 10.225 43.04 0.28 13.438947368421053 43.04 7.069999999999999 13.438947368421053 40.28 7.069999999999999 10.225</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="ba98e18f-aa5d-4a9d-8aaf-3f21da173020">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1947</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="815def8d-589c-43f4-a613-ee13f085ae55">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7569e0b0-eaeb-4583-b853-a4e80666ae96">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.53 20.2 0.14 46.53 28.94 0.14 46.53 28.94 6.5600000000000005 46.53 20.2 6.5600000000000005 46.53 20.2 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e20a0fb6-5e2b-4276-836f-c509b919fa83">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.2 20.2 0.14 40.2 28.94 0.14 46.53 28.94 0.14 46.53 20.2 0.14 40.2 20.2 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fd9ccdc5-dabf-49d5-aa63-54d940089eb6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.2 20.2 0.14 46.53 20.2 0.14 46.53 20.2 6.5600000000000005 40.2 20.2 6.5600000000000005 40.2 20.2 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="dbaadb71-c139-4015-a3cb-8ec323a25df1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.53 28.94 0.14 40.2 28.94 0.14 40.2 28.94 6.5600000000000005 46.53 28.94 6.5600000000000005 46.53 28.94 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a852f68c-248f-4d07-b7c2-5701b370760d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.2 28.94 0.14 40.2 20.2 0.14 40.2 20.2 6.5600000000000005 40.2 28.94 6.5600000000000005 40.2 28.94 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0644689b-6363-4a88-9d92-5f56745c3197">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.2 20.2 6.5600000000000005 46.53 20.2 6.5600000000000005 46.53 28.94 6.5600000000000005 40.2 28.94 6.5600000000000005 40.2 20.2 6.5600000000000005</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="b6d27324-c418-4f19-9c31-45eebddc6300">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1982</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="f5e455ea-96b7-4537-b6c8-9586dd1f6c8d">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="19d6f419-f531-42da-9f0d-4780839a4dd4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>47.14 40.3 0.14 47.14 45.2 0.14 47.14 45.2 13.219999999999999 47.14 40.3 13.219999999999999 47.14 40.3 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7b098c18-95fb-4a8d-96ca-be97369f7bcc">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.3 40.3 0.14 40.3 45.2 0.14 47.14 45.2 0.14 47.14 40.3 0.14 40.3 40.3 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a6755f08-d543-47c9-9aab-f1e1f5f0ccda">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.3 40.3 0.14 47.14 40.3 0.14 47.14 40.3 13.219999999999999 40.3 40.3 13.219999999999999 40.3 40.3 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c0faa02a-b564-4630-83fe-72f771d89dad">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>47.14 45.2 0.14 40.3 45.2 0.14 40.3 45.2 13.219999999999999 47.14 45.2 13.219999999999999 47.14 45.2 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5cc86dcd-1ead-4c00-a879-669ae09c775f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.3 45.2 0.14 40.3 40.3 0.14 40.3 40.3 13.219999999999999 40.3 45.2 13.219999999999999 40.3 45.2 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="83e30a74-e717-4921-a5f4-b28968f6f803">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.3 40.3 13.219999999999999 47.14 40.3 13.219999999999999 47.14 45.2 13.219999999999999 40.3 45.2 13.219999999999999 40.3 40.3 13.219999999999999</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45162044-732c-4d1b-9ee7-877f1376456e">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1989</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="6c102c60-cde5-4b55-a7cc-341b5636dfd3">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2aae577f-fbcd-4c11-9ea8-43e1a2ee0b0b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>42.87 60.2 0.135 42.87 67.61 0.135 42.87 67.61 12.265 42.87 60.2 12.265 42.87 60.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1099dd03-1968-4857-892a-a6a40504c885">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.2 60.2 0.135 40.2 67.61 0.135 42.87 67.61 0.135 42.87 60.2 0.135 40.2 60.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6614e1a7-cfb8-4c09-bf51-058180323edd">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.2 60.2 0.135 42.87 60.2 0.135 42.87 60.2 12.265 40.2 60.2 12.265 40.2 60.2 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7b46b11d-2113-45e3-9058-6c0f3ab68cab">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>42.87 67.61 0.135 40.2 67.61 0.135 40.2 67.61 12.265 42.87 67.61 12.265 42.87 67.61 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="512fa19a-a080-447d-b247-e7d2aad544fe">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.2 67.61 0.135 40.2 60.2 0.135 40.2 60.2 12.265 40.2 67.61 12.265 40.2 67.61 0.135</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="60e0ab7a-c42a-47a4-a9bb-0bb5184cfc90">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.2 60.2 12.265 42.87 60.2 12.265 42.87 67.61 12.265 40.2 67.61 12.265 40.2 60.2 12.265</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6eb5dd57-e0d2-4de1-8989-e3622fde68f0">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="8f81cc9d-cd35-4142-90a8-d2ccff43b893">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="48c60409-de33-4c31-bd1b-f2f4ef175f41">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>68.98 0.2 0.115 68.98 4.859999999999999 0.115 68.98 4.859999999999999 3.2350000000000003 68.98 0.2 3.2350000000000003 68.98 0.2 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e22c4c86-8825-43e4-90a7-3b189528a9ef">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 0.2 0.115 60.2 4.859999999999999 0.115 68.98 4.859999999999999 0.115 68.98 0.2 0.115 60.2 0.2 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9a762217-5bbd-4406-9d41-2d555e42d927">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 0.2 0.115 68.98 0.2 0.115 68.98 0.2 3.2350000000000003 60.2 0.2 3.2350000000000003 60.2 0.2 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9e1707b5-028a-4318-a682-7b6901565789">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>68.98 4.859999999999999 0.115 60.2 4.859999999999999 0.115 60.2 4.859999999999999 3.2350000000000003 68.98 4.859999999999999 3.2350000000000003 68.98 4.859999999999999 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="25484205-9885-4ea3-9835-db465c83cf79">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 4.859999999999999 0.115 60.2 0.2 0.115 60.2 0.2 3.2350000000000003 60.2 4.859999999999999 3.2350000000000003 60.2 4.859999999999999 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2525acd3-ee46-49e0-a758-8b13a18f0984">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 0.2 3.2350000000000003 60.2 4.859999999999999 3.2350000000000003 68.98 4.859999999999999 3.2350000000000003 68.98 0.2 3.2350000000000003 60.2 0.2 3.2350000000000003</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="cf7c7e84-39ff-4b29-9e44-551e83bab363">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 0.2 5.973997821350762 68.98 0.2 3.2350000000000003 68.98 4.859999999999999 3.2350000000000003 60.2 4.859999999999999 5.973997821350762 60.2 0.2 5.973997821350762</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="68dbc6e7-c9a1-4e76-91b1-1146f97a1b32">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 0.2 3.2350000000000003 68.98 0.2 3.2350000000000003 60.2 0.2 5.973997821350762 60.2 0.2 3.2350000000000003</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="37c37138-1982-41b6-b516-9709f77b9608">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>68.98 4.859999999999999 3.2350000000000003 60.2 4.859999999999999 3.2350000000000003 60.2 4.859999999999999 5.973997821350762 68.98 4.859999999999999 3.2350000000000003</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="27b3fd1b-b593-4d28-8012-f200acce0894">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 0.2 3.2350000000000003 60.2 0.2 5.973997821350762 60.2 4.859999999999999 5.973997821350762 60.2 4.859999999999999 3.2350000000000003 60.2 0.2 3.2350000000000003</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="101b1041-c79d-4ea5-b6cf-bf7d0967a1c6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 0.2 3.2350000000000003 68.98 0.2 3.2350000000000003 60.2 0.2 5.973997821350762 60.2 0.2 3.2350000000000003</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4c5fc44a-a23f-46c0-8fcd-982a6d0e9c89">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>68.98 4.859999999999999 3.2350000000000003 60.2 4.859999999999999 3.2350000000000003 60.2 4.859999999999999 5.973997821350762 68.98 4.859999999999999 3.2350000000000003</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4cebbbf2-e8eb-4754-8412-be1c2ab62448">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 0.2 3.2350000000000003 60.2 0.2 5.973997821350762 60.2 4.859999999999999 5.973997821350762 60.2 4.859999999999999 3.2350000000000003 60.2 0.2 3.2350000000000003</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45d9f60d-0834-41d0-9844-5b92fb1b72a9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1974</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="bc3a9152-e09f-43bb-957d-3746e825816e">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d1829452-e3ca-487c-854e-002938dc0994">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.18 20.2 0.115 63.18 26.970000000000002 0.115 63.18 26.970000000000002 3.6050000000000004 63.18 20.2 3.6050000000000004 63.18 20.2 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c15a38a9-0277-40a0-9a12-988981ff58b2">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 20.2 0.115 60.2 26.970000000000002 0.115 63.18 26.970000000000002 0.115 63.18 20.2 0.115 60.2 20.2 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a63c255d-55d8-4ab9-bf53-7fb47442b5c6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 20.2 0.115 63.18 20.2 0.115 63.18 20.2 3.6050000000000004 60.2 20.2 3.6050000000000004 60.2 20.2 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="91584782-a1b3-48cc-bd89-ff6b566faf1d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.18 26.970000000000002 0.115 60.2 26.970000000000002 0.115 60.2 26.970000000000002 3.6050000000000004 63.18 26.970000000000002 3.6050000000000004 63.18 26.970000000000002 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="247e6e23-4198-4f75-8c86-666517776e81">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 26.970000000000002 0.115 60.2 20.2 0.115 60.2 20.2 3.6050000000000004 60.2 26.970000000000002 3.6050000000000004 60.2 26.970000000000002 0.115</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="81350a49-b4ac-4e78-85cb-03550dadbbca">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 20.2 3.6050000000000004 63.18 20.2 3.6050000000000004 61.69 20.2 6.073639053254438 60.2 20.2 3.6050000000000004</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="dc6dabe9-8e74-450a-b53a-01b0938f167c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.18 20.2 3.6050000000000004 63.18 26.970000000000002 3.6050000000000004 61.69 26.970000000000002 6.073639053254438 61.69 20.2 6.073639053254438 63.18 20.2 3.6050000000000004</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3d1f279e-2c6f-4842-ba01-b42403e79025">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.18 26.970000000000002 3.6050000000000004 60.2 26.970000000000002 3.6050000000000004 61.69 26.970000000000002 6.073639053254438 63.18 26.970000000000002 3.6050000000000004</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="dce30990-89f5-460d-a707-cd455262a9ca">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 26.970000000000002 3.6050000000000004 60.2 20.2 3.6050000000000004 61.69 20.2 6.073639053254438 61.69 26.970000000000002 6.073639053254438 60.2 26.970000000000002 3.6050000000000004</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="555175a2-22c2-41a7-b85f-2fb869fc519b">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="a07f6b95-cd0a-4abe-9ed8-a77b2b374259">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="dce13856-8f64-4135-8399-bf2b8f6b286e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>62.849999999999994 40.2 0.105 62.849999999999994 45.089999999999996 0.105 62.849999999999994 45.089999999999996 3.125 62.849999999999994 40.2 3.125 62.849999999999994 40.2 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3f0214af-f94b-44ae-b688-2fb5cfd1dd89">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 40.2 0.105 60.2 45.089999999999996 0.105 62.849999999999994 45.089999999999996 0.105 62.849999999999994 40.2 0.105 60.2 40.2 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e776c9c2-9880-4f08-9246-69aafe066ab9">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 40.2 0.105 62.849999999999994 40.2 0.105 62.849999999999994 40.2 3.125 60.2 40.2 3.125 60.2 40.2 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="daeb3ef0-724a-49dd-a14a-e313886d789c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>62.849999999999994 45.089999999999996 0.105 60.2 45.089999999999996 0.105 60.2 45.089999999999996 3.125 62.849999999999994 45.089999999999996 3.125 62.849999999999994 45.089999999999996 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a8086f57-1977-4063-8192-7a102ed8f234">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 45.089999999999996 0.105 60.2 40.2 0.105 60.2 40.2 3.125 60.2 45.089999999999996 3.125 60.2 45.089999999999996 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="83c5ed74-6587-428a-b472-c54468b57462">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 40.2 3.125 60.2 45.089999999999996 3.125 62.849999999999994 45.089999999999996 3.125 62.849999999999994 40.2 3.125 60.2 40.2 3.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="35a14b7c-6f03-4398-a119-a2e392dfe9ca">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 40.2 5.741393442622951 62.849999999999994 40.2 3.125 62.849999999999994 45.089999999999996 3.125 60.2 45.089999999999996 5.741393442622951 60.2 40.2 5.741393442622951</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b9f72eb6-1e3a-4823-8f35-31cc8599facf">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 40.2 3.125 62.849999999999994 40.2 3.125 60.2 40.2 5.741393442622951 60.2 40.2 3.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="06f72022-c7a7-41bf-a179-9723c5501cb6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>62.849999999999994 45.089999999999996 3.125 60.2 45.089999999999996 3.125 60.2 45.089999999999996 5.741393442622951 62.849999999999994 45.089999999999996 3.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1125aabe-051a-415e-aeda-42968e447b4e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 40.2 3.125 60.2 40.2 5.741393442622951 60.2 45.089999999999996 5.741393442622951 60.2 45.089999999999996 3.125 60.2 40.2 3.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="8a2c3fee-5c49-440d-97e5-9179bcc424e8">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 40.2 3.125 62.849999999999994 40.2 3.125 60.2 40.2 5.741393442622951 60.2 40.2 3.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1d047d97-5f48-499d-8e77-8ced9b525a93">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>62.849999999999994 45.089999999999996 3.125 60.2 45.089999999999996 3.125 60.2 45.089999999999996 5.741393442622951 62.849999999999994 45.089999999999996 3.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3bb09772-4f0c-4b2f-b3ec-665b289a7252">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.2 40.2 3.125 60.2 40.2 5.741393442622951 60.2 45.089999999999996 5.741393442622951 60.2 45.089999999999996 3.125 60.2 40.2 3.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="32ef008b-6848-4e06-ad57-2cec22eeb093">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="91ffd345-5aae-4adf-af43-d7ca64fe3255">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7af73f09-ea14-4774-b2e4-dda4d4b4cd0f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.48 60.28 0.145 63.48 63.44 0.145 63.48 63.44 13.455 63.48 60.28 13.455 63.48 60.28 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0f6c2733-3053-448c-ba80-18b3b39942f3">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.28 60.28 0.145 60.28 63.44 0.145 63.48 63.44 0.145 63.48 60.28 0.145 60.28 60.28 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a5523477-6328-4d2a-92c6-6bad1633a1fa">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.28 60.28 0.145 63.48 60.28 0.145 63.48 60.28 13.455 60.28 60.28 13.455 60.28 60.28 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="115f2e2e-99dd-4c2c-b37c-726eda75f8ab">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.48 63.44 0.145 60.28 63.44 0.145 60.28 63.44 13.455 63.48 63.44 13.455 63.48 63.44 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="353b0826-10bf-428d-9fa6-44bb412f22c4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.28 63.44 0.145 60.28 60.28 0.145 60.28 60.28 13.455 60.28 63.44 13.455 60.28 63.44 0.145</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0d626de6-a7de-4f15-9f06-0ff43dba3a77">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.28 60.28 13.455 63.48 60.28 13.455 63.48 63.44 13.455 60.28 63.44 13.455 60.28 60.28 13.455</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="a64f3754-2a76-4790-ad49-598f014e6814">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="59526413-1019-4e34-a4fd-43c9ff59d2d5">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1dcf0cb0-cd8d-48bd-95ff-a0ac296fefa9">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>84.01 0.38 0.125 84.01 9.42 0.125 84.01 9.42 13.875 84.01 0.38 13.875 84.01 0.38 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f56a659d-2484-470f-865e-3bb2d2e68892">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.38 0.38 0.125 80.38 9.42 0.125 84.01 9.42 0.125 84.01 0.38 0.125 80.38 0.38 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="db9d7dd2-ad85-4a51-b6af-036682cbb7a9">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.38 0.38 0.125 84.01 0.38 0.125 84.01 0.38 13.875 80.38 0.38 13.875 80.38 0.38 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="056331f9-9630-432e-9ede-ec898a027342">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>84.01 9.42 0.125 80.38 9.42 0.125 80.38 9.42 13.875 84.01 9.42 13.875 84.01 9.42 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ac8a2b8d-a6bd-41a2-92f3-1be6242e7b90">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.38 9.42 0.125 80.38 0.38 0.125 80.38 0.38 13.875 80.38 9.42 13.875 80.38 9.42 0.125</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="698dc35f-b782-42e7-a341-b5e0a8319b93">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.38 0.38 13.875 84.01 0.38 13.875 84.01 9.42 13.875 80.38 9.42 13.875 80.38 0.38 13.875</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="4e73a2b8-54cc-4722-a8b8-57971461b270">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1952</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="f62af443-5ab2-4e71-958a-658ab8eca9ce">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a320ad0d-908d-4485-9198-dd54381cdffa">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>85.07 20.2 0.105 85.07 23.93 0.105 85.07 23.93 7.025 85.07 20.2 7.025 85.07 20.2 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="06457c63-25fe-4801-b179-65ed5d69bb38">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 20.2 0.105 80.2 23.93 0.105 85.07 23.93 0.105 85.07 20.2 0.105 80.2 20.2 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1744d5c5-fe55-48a0-8e86-dd96d3a39bf1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 20.2 0.105 85.07 20.2 0.105 85.07 20.2 7.025 80.2 20.2 7.025 80.2 20.2 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f577080c-39f7-4210-907f-48d88fe32a25">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>85.07 23.93 0.105 80.2 23.93 0.105 80.2 23.93 7.025 85.07 23.93 7.025 85.07 23.93 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="bda92b72-1add-47de-8192-6c859554bcf6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 23.93 0.105 80.2 20.2 0.105 80.2 20.2 7.025 80.2 23.93 7.025 80.2 23.93 0.105</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5f4e7bb6-b698-47aa-b345-c7ca3bc65e8d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 20.2 7.025 80.2 23.93 7.025 85.07 23.93 7.025 85.07 20.2 7.025 80.2 20.2 7.025</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="8e68e84a-c9e6-434d-a5b3-5341df4d3da0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 20.2 9.401261859582544 85.07 20.2 7.025 85.07 23.93 7.025 80.2 23.93 9.401261859582544 80.2 20.2 9.401261859582544</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ce180741-aad7-4688-bb9b-94ad0a6bb2c6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 20.2 7.025 85.07 20.2 7.025 80.2 20.2 9.401261859582544 80.2 20.2 7.025</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="65a5f9b0-19a0-4b08-9579-5ba6a1769a1a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>85.07 23.93 7.025 80.2 23.93 7.025 80.2 23.93 9.401261859582544 85.07 23.93 7.025</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d3180767-34d9-4fe1-83a0-55b8991e677e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 20.2 7.025 80.2 20.2 9.401261859582544 80.2 23.93 9.401261859582544 80.2 23.93 7.025 80.2 20.2 7.025</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="90f66d9b-bc0f-4eea-9814-dcb6089f480d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 20.2 7.025 85.07 20.2 7.025 80.2 20.2 9.401261859582544 80.2 20.2 7.025</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a5dd7ad4-84e6-42d6-b9bc-2afaaf8d9c76">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>85.07 23.93 7.025 80.2 23.93 7.025 80.2 23.93 9.401261859582544 85.07 23.93 7.025</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="25a3e6d7-37da-4be9-84b4-a1a62d1f95ce">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 20.2 7.025 80.2 20.2 9.401261859582544 80.2 23.93 9.401261859582544 80.2 23.93 7.025 80.2 20.2 7.025</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="44e2c197-1881-4ec3-bc14-f284bfa8716c">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="2025b2ce-9032-4f36-8678-6a411e1c3009">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4c9ba245-5abc-4f9e-a612-021c6393d5f7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.24 40.28 0.14 83.24 49.339999999999996 0.14 83.24 49.339999999999996 15.36 83.24 40.28 15.36 83.24 40.28 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7be87ba2-3ea8-49b6-a5fd-02d6438aabd0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.28 40.28 0.14 80.28 49.339999999999996 0.14 83.24 49.339999999999996 0.14 83.24 40.28 0.14 80.28 40.28 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0e117ea7-0ed6-40f8-a593-7c8932400a60">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.28 40.28 0.14 83.24 40.28 0.14 83.24 40.28 15.36 80.28 40.28 15.36 80.28 40.28 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2616c7ae-1d84-48ca-91e3-3462bbb3deae">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.24 49.339999999999996 0.14 80.28 49.339999999999996 0.14 80.28 49.339999999999996 15.36 83.24 49.339999999999996 15.36 83.24 49.339999999999996 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6a23bb80-7b93-4961-b1dd-e52441cbb440">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.28 49.339999999999996 0.14 80.28 40.28 0.14 80.28 40.28 15.36 80.28 49.339999999999996 15.36 80.28 49.339999999999996 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="23d3c87c-c6ed-4870-aa90-da483af2a39d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.28 40.28 15.36 83.24 40.28 15.36 83.24 49.339999999999996 15.36 80.28 49.339999999999996 15.36 80.28 40.28 15.36</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="708daa94-e4a5-413b-8efb-3d9bc59e9f58">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod2Solid>
        <gml:Solid gml:id="dbb69817-fd6e-42d3-9b46-e5c481300d12">
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5761b26d-a2b9-405a-9f4f-7e8d6bb0ce67">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.71 60.2 0.14 83.71 68.05 0.14 83.71 68.05 9.23 83.71 60.2 9.23 83.71 60.2 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a9012b2f-7c7c-4ad2-a399-0f3f4674a66a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 60.2 0.14 80.2 68.05 0.14 83.71 68.05 0.14 83.71 60.2 0.14 80.2 60.2 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="79336ca9-e420-446b-a35d-97430773f2af">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 60.2 0.14 83.71 60.2 0.14 83.71 60.2 9.23 80.2 60.2 9.23 80.2 60.2 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="475c486d-3306-4812-a362-0fee79ba13c4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.71 68.05 0.14 80.2 68.05 0.14 80.2 68.05 9.23 83.71 68.05 9.23 83.71 68.05 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="35342385-d420-4762-94a6-7c8ff614f8b8">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 68.05 0.14 80.2 60.2 0.14 80.2 60.2 9.23 80.2 68.05 9.23 80.2 68.05 0.14</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d0f3f68c-3f45-42db-95dc-3fdbc951ca68">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 60.2 9.23 83.71 60.2 9.23 81.955 61.61 11.770485933503837 80.2 60.2 9.23</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d92086c7-8299-47ec-84f5-874fac2b2afa">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.71 60.2 9.23 83.71 68.05 9.23 81.955 66.64 11.770485933503837 81.955 61.61 11.770485933503837 83.71 60.2 9.23</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="cbcc5072-c957-471e-afcd-9ad8fc98bdc5">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.71 68.05 9.23 80.2 68.05 9.23 81.955 66.64 11.770485933503837 83.71 68.05 9.23</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon gml:id="81d8bf26-4f74-466c-9128-598f6396119a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.2 68.05 9.23 80.2 60.2 9.23 81.955 61.61 11.770485933503837 81.955 66.64 11.770485933503837 80.2 68.05 9.23</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod2Solid>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
