<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns="http://www.opengis.net/citygml/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:fme="http://www.safe.com/xml/xmltables">
  <gml:name>LOD1_3_F0_H3</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="9fd16237-61d1-494c-b265-4e51b42046ed">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1969</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="e51b3d97-a56b-472f-b469-cfaa90fb1311">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 3.34 0.0 0.0 3.34 0.0 17.45 0.0 0.0 17.45 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="4c41b051-c911-464a-93f7-2ff0e99d21a7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>3.34 7.77 0.0 0.0 7.77 0.0 0.0 7.77 17.45 3.34 7.77 17.45 3.34 7.77 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="9a65ffc5-f4c9-4bc8-9cf1-92a6b5ee7814">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 7.77 0.0 0.0 0.0 0.0 0.0 0.0 17.45 0.0 7.77 17.45 0.0 7.77 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="87185767-9e00-42bf-95b5-77934fceef25">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>3.34 0.0 0.0 3.34 7.77 0.0 3.34 7.77 17.45 3.34 0.0 17.45 3.34 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="5a844396-8e4f-40f9-bd9f-9168f69fa04b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 0.0 7.77 0.0 3.34 7.77 0.0 3.34 0.0 0.0 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="7e16ac54-eb99-489b-83c4-774beb968d8e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 17.45 3.34 0.0 17.45 3.34 7.77 17.45 0.0 7.77 17.45 0.0 0.0 17.45</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6e58349d-cbc4-4c44-95e6-5e550d5d0899">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="c8031e73-44e7-48c4-b25c-521a5fd96d54">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 0.0 5.72 20.0 0.0 5.72 20.0 4.67 0.0 20.0 4.67 0.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="5b1d6435-1781-49ee-9702-ad72c7c9301d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>5.72 29.6 0.0 0.0 29.6 0.0 0.0 29.6 4.67 5.72 29.6 4.67 5.72 29.6 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="82c86a0e-c6a5-44c3-bfc6-eb2e2e6bdcab">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 29.6 0.0 0.0 20.0 0.0 0.0 20.0 4.67 0.0 29.6 4.67 0.0 29.6 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="3b771109-31c9-4eaa-9124-fae1044cd15b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>5.72 20.0 0.0 5.72 29.6 0.0 5.72 29.6 4.67 5.72 20.0 4.67 5.72 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="babf542f-0a3a-4f80-85b7-4e0408b87f35">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 0.0 0.0 29.6 0.0 5.72 29.6 0.0 5.72 20.0 0.0 0.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="3673a11b-344f-40b0-b452-29c2f929a891">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 4.67 5.72 20.0 4.67 5.72 29.6 4.67 0.0 29.6 4.67 0.0 20.0 4.67</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="92a9ffcc-a809-436b-ab8f-213341025556">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1965</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="fe0034a7-3e92-48e7-aa8f-915e3d283911">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 0.0 7.38 40.0 0.0 7.38 40.0 16.1 0.0 40.0 16.1 0.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="d21d3e2e-0865-401a-8900-9f410b20a7d7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>7.38 43.04 0.0 0.0 43.04 0.0 0.0 43.04 16.1 7.38 43.04 16.1 7.38 43.04 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="82248e73-2c01-4130-8482-c668dab10fe5">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 43.04 0.0 0.0 40.0 0.0 0.0 40.0 16.1 0.0 43.04 16.1 0.0 43.04 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ad67de17-fb7a-4cb6-bd93-82f4fe5912d7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>7.38 40.0 0.0 7.38 43.04 0.0 7.38 43.04 16.1 7.38 40.0 16.1 7.38 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="12f013c9-b687-461d-b03d-df4d13667908">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 0.0 0.0 43.04 0.0 7.38 43.04 0.0 7.38 40.0 0.0 0.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="be5e7bb2-fa9d-46a3-b6b8-e4d1f022d298">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 16.1 7.38 40.0 16.1 7.38 43.04 16.1 0.0 43.04 16.1 0.0 40.0 16.1</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="580bc1f5-b498-4048-a45b-e65a9d18c75a">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1990</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="93aca7d5-a966-4a3a-8f69-3b5167bfef60">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 60.0 0.0 9.27 60.0 0.0 9.27 60.0 7.42 0.0 60.0 7.42 0.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f36fd378-d666-4af0-965d-befc2d596f9f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>9.27 63.37 0.0 0.0 63.37 0.0 0.0 63.37 7.42 9.27 63.37 7.42 9.27 63.37 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="0e8fbf11-5817-41ec-8a15-8f25fecfa81a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 63.37 0.0 0.0 60.0 0.0 0.0 60.0 7.42 0.0 63.37 7.42 0.0 63.37 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="27944081-7c0e-4120-b0e3-61eb1ab91ab3">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>9.27 60.0 0.0 9.27 63.37 0.0 9.27 63.37 7.42 9.27 60.0 7.42 9.27 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="cbf89f6b-416f-410f-b826-a4b33caff8f1">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 60.0 0.0 0.0 63.37 0.0 9.27 63.37 0.0 9.27 60.0 0.0 0.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="197b5545-e1df-40f9-8a5b-80640e68344e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 60.0 7.42 9.27 60.0 7.42 9.27 63.37 7.42 0.0 63.37 7.42 0.0 60.0 7.42</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="95a4abfb-cd95-422f-9c27-ebea911dcc4f">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1967</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="4088ac70-30ee-4600-bd6c-e1bc535563e8">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 0.0 23.990000000000002 0.0 0.0 23.990000000000002 0.0 10.206002506265664 20.0 0.0 10.206002506265664 20.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="fb6066a0-817c-4ba5-8cba-de0ca49680d6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.990000000000002 5.74 0.0 20.0 5.74 0.0 20.0 5.74 10.206002506265664 23.990000000000002 5.74 10.206002506265664 23.990000000000002 5.74 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="501ddc57-4cbb-4b0a-b80e-74d86893ba28">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 5.74 0.0 20.0 0.0 0.0 20.0 0.0 10.206002506265664 20.0 5.74 10.206002506265664 20.0 5.74 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="46b6d9d5-c5ad-4ebc-9c68-d0c35ad5ad22">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.990000000000002 0.0 0.0 23.990000000000002 5.74 0.0 23.990000000000002 5.74 10.206002506265664 23.990000000000002 0.0 10.206002506265664 23.990000000000002 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="048c057a-81b5-4d7c-bd2f-f92b7d8074e3">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 0.0 20.0 5.74 0.0 23.990000000000002 5.74 0.0 23.990000000000002 0.0 0.0 20.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a27b6178-d1f5-40bc-a05d-6547c46b3e73">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 10.206002506265664 23.990000000000002 0.0 10.206002506265664 23.990000000000002 5.74 10.206002506265664 20.0 5.74 10.206002506265664 20.0 0.0 10.206002506265664</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="3d5dea93-0b71-41ff-b5f5-438bad25f186">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1959</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="67658d71-b47f-4ea7-8a08-75632e8b6c8a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 0.0 23.11 20.0 0.0 23.11 20.0 10.457604501607719 20.0 20.0 10.457604501607719 20.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="9aa23667-49d1-4189-8100-9e3b72ab9acd">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.11 28.83 0.0 20.0 28.83 0.0 20.0 28.83 10.457604501607719 23.11 28.83 10.457604501607719 23.11 28.83 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="72b824b7-4fb9-4966-97e2-cda368a6bf7c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 28.83 0.0 20.0 20.0 0.0 20.0 20.0 10.457604501607719 20.0 28.83 10.457604501607719 20.0 28.83 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c67476ee-df16-43ed-a6d8-06110df4ea42">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.11 20.0 0.0 23.11 28.83 0.0 23.11 28.83 10.457604501607719 23.11 20.0 10.457604501607719 23.11 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="5ccafba2-c2ae-484e-9dea-28f83a58cb1d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 0.0 20.0 28.83 0.0 23.11 28.83 0.0 23.11 20.0 0.0 20.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="20e17932-4500-4d2b-9999-6fbd30d7bfa5">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 10.457604501607719 23.11 20.0 10.457604501607719 23.11 28.83 10.457604501607719 20.0 28.83 10.457604501607719 20.0 20.0 10.457604501607719</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="60bc0619-7b36-44bd-ae91-da3c4563c587">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1948</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="741b98d4-3daf-4047-97f3-a03095c2b828">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 0.0 23.16 40.0 0.0 23.16 40.0 10.92 20.0 40.0 10.92 20.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="50ad6079-7177-4567-be92-b1399c84768b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.16 48.730000000000004 0.0 20.0 48.730000000000004 0.0 20.0 48.730000000000004 10.92 23.16 48.730000000000004 10.92 23.16 48.730000000000004 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="9c6f4e39-d43f-43c5-abbc-ac1c48e910dc">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 48.730000000000004 0.0 20.0 40.0 0.0 20.0 40.0 10.92 20.0 48.730000000000004 10.92 20.0 48.730000000000004 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="1cacc886-53cc-43b3-b89a-73a1e482db29">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.16 40.0 0.0 23.16 48.730000000000004 0.0 23.16 48.730000000000004 10.92 23.16 40.0 10.92 23.16 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="aa167fd9-6356-41ea-9535-76e310fb7f40">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 0.0 20.0 48.730000000000004 0.0 23.16 48.730000000000004 0.0 23.16 40.0 0.0 20.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="3676c754-2e71-4b08-9eae-36dbb262fe65">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 10.92 23.16 40.0 10.92 23.16 48.730000000000004 10.92 20.0 48.730000000000004 10.92 20.0 40.0 10.92</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="d333dfad-c0a0-4cad-8565-a93c5e17ce8d">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>2009</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="511a93ed-a13d-4815-a5ea-f2579115507b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 60.0 0.0 28.36 60.0 0.0 28.36 60.0 6.8 20.0 60.0 6.8 20.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="3bf5c885-8dc9-46dd-a326-67f879f84790">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>28.36 64.12 0.0 20.0 64.12 0.0 20.0 64.12 6.8 28.36 64.12 6.8 28.36 64.12 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="629a13de-c858-435d-b248-6128bdfefa02">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 64.12 0.0 20.0 60.0 0.0 20.0 60.0 6.8 20.0 64.12 6.8 20.0 64.12 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="fbfd783b-c4a2-4507-86b2-25e159398aa9">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>28.36 60.0 0.0 28.36 64.12 0.0 28.36 64.12 6.8 28.36 60.0 6.8 28.36 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="58976ec2-7d3b-4494-a3ba-354f238dd1da">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 60.0 0.0 20.0 64.12 0.0 28.36 64.12 0.0 28.36 60.0 0.0 20.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="27669c9a-4be9-4eb1-84c0-27acdd7c24ff">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 60.0 6.8 28.36 60.0 6.8 28.36 64.12 6.8 20.0 64.12 6.8 20.0 60.0 6.8</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="fcbb6855-ac3c-4a96-97b2-4a33bbfeede9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="c7b2bd47-c99a-48e4-bae0-d868a905610e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 0.0 46.08 0.0 0.0 46.08 0.0 11.337631578947368 40.0 0.0 11.337631578947368 40.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="4f02ff98-3e78-4978-ad20-372fd1d6fa09">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.08 7.35 0.0 40.0 7.35 0.0 40.0 7.35 11.337631578947368 46.08 7.35 11.337631578947368 46.08 7.35 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a61ac9cd-565b-4cf8-acd0-a6261a2b9d16">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 7.35 0.0 40.0 0.0 0.0 40.0 0.0 11.337631578947368 40.0 7.35 11.337631578947368 40.0 7.35 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f547170e-5f79-45fc-86cf-2a74b63c9135">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.08 0.0 0.0 46.08 7.35 0.0 46.08 7.35 11.337631578947368 46.08 0.0 11.337631578947368 46.08 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="afd956e1-75f4-46f6-8229-a5649acee101">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 0.0 40.0 7.35 0.0 46.08 7.35 0.0 46.08 0.0 0.0 40.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2ab09d05-e342-454d-ae29-f9ba0c7e1562">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 11.337631578947368 46.08 0.0 11.337631578947368 46.08 7.35 11.337631578947368 40.0 7.35 11.337631578947368 40.0 0.0 11.337631578947368</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="ba98e18f-aa5d-4a9d-8aaf-3f21da173020">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1947</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="51dce8e1-2f5a-4891-a776-518e1ceac510">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 0.0 46.730000000000004 20.0 0.0 46.730000000000004 20.0 6.7 40.0 20.0 6.7 40.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="edb83355-1c47-4aea-8009-3f294d45efb5">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.730000000000004 29.14 0.0 40.0 29.14 0.0 40.0 29.14 6.7 46.730000000000004 29.14 6.7 46.730000000000004 29.14 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="fbb8104e-2f9a-41b2-ab2d-4f283bcc03e4">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 29.14 0.0 40.0 20.0 0.0 40.0 20.0 6.7 40.0 29.14 6.7 40.0 29.14 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="6f39b0b9-44f0-481a-83d9-935be1495341">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.730000000000004 20.0 0.0 46.730000000000004 29.14 0.0 46.730000000000004 29.14 6.7 46.730000000000004 20.0 6.7 46.730000000000004 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="e025cd4c-e395-4f86-9e2d-daa0a2ef8d74">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 0.0 40.0 29.14 0.0 46.730000000000004 29.14 0.0 46.730000000000004 20.0 0.0 40.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="50e82ba4-5da8-46ec-b7b4-ee7e5065835c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 6.7 46.730000000000004 20.0 6.7 46.730000000000004 29.14 6.7 40.0 29.14 6.7 40.0 20.0 6.7</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="b6d27324-c418-4f19-9c31-45eebddc6300">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1982</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="cde2d21c-db36-4ac8-805c-2d20b4c31da7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 0.0 47.44 40.0 0.0 47.44 40.0 13.36 40.0 40.0 13.36 40.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f447a6b3-20cb-4190-b8ef-0847cc1a024d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>47.44 45.5 0.0 40.0 45.5 0.0 40.0 45.5 13.36 47.44 45.5 13.36 47.44 45.5 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b1d63788-4325-4149-ba1e-fdcb20969683">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 45.5 0.0 40.0 40.0 0.0 40.0 40.0 13.36 40.0 45.5 13.36 40.0 45.5 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f6eee8b6-bb97-4750-a86c-5a7eca2a4118">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>47.44 40.0 0.0 47.44 45.5 0.0 47.44 45.5 13.36 47.44 40.0 13.36 47.44 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="79efe88f-fcec-41a7-94da-2145bfff87c7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 0.0 40.0 45.5 0.0 47.44 45.5 0.0 47.44 40.0 0.0 40.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ac82f5a1-fead-4aac-ab1c-714d119633d6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 13.36 47.44 40.0 13.36 47.44 45.5 13.36 40.0 45.5 13.36 40.0 40.0 13.36</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45162044-732c-4d1b-9ee7-877f1376456e">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1989</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="336acad2-21f3-4557-af3a-f86d23c7989f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 60.0 0.0 43.07 60.0 0.0 43.07 60.0 12.4 40.0 60.0 12.4 40.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="4f053b1c-ebd0-4c55-9bf2-cf40f679ca42">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>43.07 67.81 0.0 40.0 67.81 0.0 40.0 67.81 12.4 43.07 67.81 12.4 43.07 67.81 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="90ecc7e6-71b5-43ed-9c32-c8faf0d33ce0">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 67.81 0.0 40.0 60.0 0.0 40.0 60.0 12.4 40.0 67.81 12.4 40.0 67.81 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="7d119318-b521-45f8-96b8-bd38d2e1e3ac">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>43.07 60.0 0.0 43.07 67.81 0.0 43.07 67.81 12.4 43.07 60.0 12.4 43.07 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="7aaf13da-561d-4ef7-b1fd-28d7ac2d0af2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 60.0 0.0 40.0 67.81 0.0 43.07 67.81 0.0 43.07 60.0 0.0 40.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="646fa55a-bb54-4d18-b7dc-2070cef6ca4f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 60.0 12.4 43.07 60.0 12.4 43.07 67.81 12.4 40.0 67.81 12.4 40.0 60.0 12.4</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6eb5dd57-e0d2-4de1-8989-e3622fde68f0">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="15e1182d-a2ce-4eb9-bb5f-f19377bd355b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 69.18 0.0 0.0 69.18 0.0 4.52 60.0 0.0 4.52 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="aaf2d3f1-cba9-4340-ab7e-6b8aa47bfb8b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>69.18 5.06 0.0 60.0 5.06 0.0 60.0 5.06 4.52 69.18 5.06 4.52 69.18 5.06 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="268b8b2e-11b1-4bb5-8f35-5a00e40fd718">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 5.06 0.0 60.0 0.0 0.0 60.0 0.0 4.52 60.0 5.06 4.52 60.0 5.06 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="3d2dcfe2-12fa-48ec-b6b2-25643d4fa3e1">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>69.18 0.0 0.0 69.18 5.06 0.0 69.18 5.06 4.52 69.18 0.0 4.52 69.18 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="06a06f2a-2562-48ac-a37d-17e9bb79b98f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 60.0 5.06 0.0 69.18 5.06 0.0 69.18 0.0 0.0 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="349bcd63-c6fb-4368-b025-3cf9ec4bcede">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 4.52 69.18 0.0 4.52 69.18 5.06 4.52 60.0 5.06 4.52 60.0 0.0 4.52</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45d9f60d-0834-41d0-9844-5b92fb1b72a9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1974</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="5374a089-7866-417a-9c08-39269f2ca06d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 20.0 0.0 63.38 20.0 0.0 63.38 20.0 4.4592307692307696 60.0 20.0 4.4592307692307696 60.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c0083193-8c61-4e2e-a5f0-67574df667d7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.38 27.17 0.0 60.0 27.17 0.0 60.0 27.17 4.4592307692307696 63.38 27.17 4.4592307692307696 63.38 27.17 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="d55f4aba-7144-48d2-b19e-07d738a1f8af">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 27.17 0.0 60.0 20.0 0.0 60.0 20.0 4.4592307692307696 60.0 27.17 4.4592307692307696 60.0 27.17 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="fb3844be-add1-483e-a699-db54a2609da2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.38 20.0 0.0 63.38 27.17 0.0 63.38 27.17 4.4592307692307696 63.38 20.0 4.4592307692307696 63.38 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="89e710dc-53e7-4184-bc13-4cff8e4162f5">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 20.0 0.0 60.0 27.17 0.0 63.38 27.17 0.0 63.38 20.0 0.0 60.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2d5f3738-1d5a-45d8-b1a3-683a2b2c2efa">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 20.0 4.4592307692307696 63.38 20.0 4.4592307692307696 63.38 27.17 4.4592307692307696 60.0 27.17 4.4592307692307696 60.0 20.0 4.4592307692307696</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="555175a2-22c2-41a7-b85f-2fb869fc519b">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="7527f193-2be0-4f32-ab45-4cf4ad5bf7e6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 40.0 0.0 63.05 40.0 0.0 63.05 40.0 4.42 60.0 40.0 4.42 60.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="9207a40f-f6bc-4ffe-b9d3-9e1760892323">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.05 45.29 0.0 60.0 45.29 0.0 60.0 45.29 4.42 63.05 45.29 4.42 63.05 45.29 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a16f1f54-6ca0-4501-907d-2966b74d0012">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 45.29 0.0 60.0 40.0 0.0 60.0 40.0 4.42 60.0 45.29 4.42 60.0 45.29 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="97dee2ab-5ffb-4364-8e4b-665b6ca1957a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.05 40.0 0.0 63.05 45.29 0.0 63.05 45.29 4.42 63.05 40.0 4.42 63.05 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="29fdc358-6324-42a4-b981-3ff8bb3aa6c1">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 40.0 0.0 60.0 45.29 0.0 63.05 45.29 0.0 63.05 40.0 0.0 60.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="034f8894-ebe5-480f-8c7e-bf047ec4ff32">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 40.0 4.42 63.05 40.0 4.42 63.05 45.29 4.42 60.0 45.29 4.42 60.0 40.0 4.42</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="32ef008b-6848-4e06-ad57-2cec22eeb093">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="5ca2e91e-12db-4edb-854e-cede3be52e7c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 60.0 0.0 63.76 60.0 0.0 63.76 60.0 13.6 60.0 60.0 13.6 60.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f6f51894-b083-449f-9c86-b889b34460ad">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.76 63.72 0.0 60.0 63.72 0.0 60.0 63.72 13.6 63.76 63.72 13.6 63.76 63.72 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="7081627c-494c-47e3-a03f-1e6ee5754cb8">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 63.72 0.0 60.0 60.0 0.0 60.0 60.0 13.6 60.0 63.72 13.6 60.0 63.72 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="806c4599-ce85-4b37-aca5-a060c2659f15">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.76 60.0 0.0 63.76 63.72 0.0 63.76 63.72 13.6 63.76 60.0 13.6 63.76 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="4bfc6fc0-439e-46af-96e4-e568d0a2b576">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 60.0 0.0 60.0 63.72 0.0 63.76 63.72 0.0 63.76 60.0 0.0 60.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="dd38001e-42be-43a6-ab2f-a2f3e1387b82">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 60.0 13.6 63.76 60.0 13.6 63.76 63.72 13.6 60.0 63.72 13.6 60.0 60.0 13.6</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="a64f3754-2a76-4790-ad49-598f014e6814">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="3cff5bb5-9c70-49eb-bafa-348c679d35f6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 0.0 0.0 84.39 0.0 0.0 84.39 0.0 14.0 80.0 0.0 14.0 80.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="d7b45e9f-498d-424d-b5f7-b242bc408f02">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>84.39 9.8 0.0 80.0 9.8 0.0 80.0 9.8 14.0 84.39 9.8 14.0 84.39 9.8 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="8adf4d88-3e22-4a5d-8f49-298b841c4c50">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 9.8 0.0 80.0 0.0 0.0 80.0 0.0 14.0 80.0 9.8 14.0 80.0 9.8 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="83e04d31-06fe-4de5-a305-99a1cb59e9a8">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>84.39 0.0 0.0 84.39 9.8 0.0 84.39 9.8 14.0 84.39 0.0 14.0 84.39 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="86832bbd-091d-44ea-beae-f8e82e9a20c6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 0.0 0.0 80.0 9.8 0.0 84.39 9.8 0.0 84.39 0.0 0.0 80.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="08544294-3c20-44bf-a6ca-f2b4c279e997">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 0.0 14.0 84.39 0.0 14.0 84.39 9.8 14.0 80.0 9.8 14.0 80.0 0.0 14.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="4e73a2b8-54cc-4722-a8b8-57971461b270">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1952</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="b7839390-bf00-4b71-b76b-13ada2d10c5d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 20.0 0.0 85.27 20.0 0.0 85.27 20.0 8.155 80.0 20.0 8.155 80.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f6c53b25-91ee-4c10-bb44-a21b477f8c8e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>85.27 24.13 0.0 80.0 24.13 0.0 80.0 24.13 8.155 85.27 24.13 8.155 85.27 24.13 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="98092b78-5060-4061-8e80-a29a4e456240">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 24.13 0.0 80.0 20.0 0.0 80.0 20.0 8.155 80.0 24.13 8.155 80.0 24.13 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="39212ff3-1e4f-4939-a649-a5fcb0b967b0">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>85.27 20.0 0.0 85.27 24.13 0.0 85.27 24.13 8.155 85.27 20.0 8.155 85.27 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="d4cfa98c-2f7b-49d9-b5ed-88a2bc7901e6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 20.0 0.0 80.0 24.13 0.0 85.27 24.13 0.0 85.27 20.0 0.0 80.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="64e041be-d425-49de-8163-636700432957">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 20.0 8.155 85.27 20.0 8.155 85.27 24.13 8.155 80.0 24.13 8.155 80.0 20.0 8.155</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="44e2c197-1881-4ec3-bc14-f284bfa8716c">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="d7bbba18-2957-47da-9728-b2778e092351">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 40.0 0.0 83.52 40.0 0.0 83.52 40.0 15.5 80.0 40.0 15.5 80.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f71b584e-6875-43d2-a096-e473bf9a405a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>83.52 49.62 0.0 80.0 49.62 0.0 80.0 49.62 15.5 83.52 49.62 15.5 83.52 49.62 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="388ddf0c-c693-4512-87ed-a8757da13a6c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 49.62 0.0 80.0 40.0 0.0 80.0 40.0 15.5 80.0 49.62 15.5 80.0 49.62 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="05f04db8-ef50-4972-b0b2-bffef04e8390">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>83.52 40.0 0.0 83.52 49.62 0.0 83.52 49.62 15.5 83.52 40.0 15.5 83.52 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c1946d9c-0b28-4c87-bc6d-f75a98b90ac3">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 40.0 0.0 80.0 49.62 0.0 83.52 49.62 0.0 83.52 40.0 0.0 80.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="02083dd9-d05d-4524-8509-53caf9fbd27b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 40.0 15.5 83.52 40.0 15.5 83.52 49.62 15.5 80.0 49.62 15.5 80.0 40.0 15.5</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="708daa94-e4a5-413b-8efb-3d9bc59e9f58">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="50c25c4e-4f20-49fc-92b4-5e2906390a4d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 60.0 0.0 83.91 60.0 0.0 83.91 60.0 10.005588235294118 80.0 60.0 10.005588235294118 80.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="395740fb-59f9-4f6d-b06e-387b7b17cf04">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>83.91 68.25 0.0 80.0 68.25 0.0 80.0 68.25 10.005588235294118 83.91 68.25 10.005588235294118 83.91 68.25 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ea4ec7ec-ce49-47df-80fa-f85402cf1c21">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 68.25 0.0 80.0 60.0 0.0 80.0 60.0 10.005588235294118 80.0 68.25 10.005588235294118 80.0 68.25 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b62f9698-c61a-4dea-8bf2-a5b9c15bc50d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>83.91 60.0 0.0 83.91 68.25 0.0 83.91 68.25 10.005588235294118 83.91 60.0 10.005588235294118 83.91 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="85c10bab-41e7-4c4e-b555-d20bba493211">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 60.0 0.0 80.0 68.25 0.0 83.91 68.25 0.0 83.91 60.0 0.0 80.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="02200b0b-1358-49d6-80fc-517f341dca3e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 60.0 10.005588235294118 83.91 60.0 10.005588235294118 83.91 68.25 10.005588235294118 80.0 68.25 10.005588235294118 80.0 60.0 10.005588235294118</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
