<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns="http://www.opengis.net/citygml/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:fme="http://www.safe.com/xml/xmltables">
  <gml:name>LOD1_2_F0_H3</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="9fd16237-61d1-494c-b265-4e51b42046ed">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1969</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="12c460cb-b81d-4fe8-93d9-bda322fa3f9c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 3.34 0.0 0.0 3.34 0.0 17.45 0.0 0.0 17.45 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="87abe697-aa76-4d48-aec6-709c614e29f4">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>3.34 7.77 0.0 0.0 7.77 0.0 0.0 7.77 17.45 3.34 7.77 17.45 3.34 7.77 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c16cd8ba-df7e-42aa-a122-a02f6d931812">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 7.77 0.0 0.0 0.0 0.0 0.0 0.0 17.45 0.0 7.77 17.45 0.0 7.77 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="51d2fedd-19e9-4d19-abf6-b06aa0411dea">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>3.34 0.0 0.0 3.34 7.77 0.0 3.34 7.77 17.45 3.34 0.0 17.45 3.34 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ffad25f6-0ff4-49fa-a70e-e5c59e2a440d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 0.0 7.77 0.0 3.34 7.77 0.0 3.34 0.0 0.0 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ee2a7bf8-ff79-47f9-ae97-9a9027e7319d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 17.45 3.34 0.0 17.45 3.34 7.77 17.45 0.0 7.77 17.45 0.0 0.0 17.45</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6e58349d-cbc4-4c44-95e6-5e550d5d0899">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="fe200bff-cd0a-40d3-bf67-1b4fbcbec820">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 0.0 5.72 20.0 0.0 5.72 20.0 4.67 0.0 20.0 4.67 0.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="1e3aec27-8942-451a-bfbd-1d7441e20f54">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>5.72 29.6 0.0 0.0 29.6 0.0 0.0 29.6 4.67 5.72 29.6 4.67 5.72 29.6 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="86653f2d-1730-4188-b876-89f02143ede7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 29.6 0.0 0.0 20.0 0.0 0.0 20.0 4.67 0.0 29.6 4.67 0.0 29.6 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="41f6721c-21a3-48fe-b871-7ee8b4c4f8b7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>5.72 20.0 0.0 5.72 29.6 0.0 5.72 29.6 4.67 5.72 20.0 4.67 5.72 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c371519e-da6e-4e31-a8d2-81928626af7d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 0.0 0.0 29.6 0.0 5.72 29.6 0.0 5.72 20.0 0.0 0.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a00e1123-d572-4ec0-8d4c-3244ed4250fa">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 20.0 4.67 5.72 20.0 4.67 5.72 29.6 4.67 0.0 29.6 4.67 0.0 20.0 4.67</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="92a9ffcc-a809-436b-ab8f-213341025556">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1965</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="30248c94-927a-42d8-bba1-11e9a3ef076b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 0.0 7.38 40.0 0.0 7.38 40.0 16.1 0.0 40.0 16.1 0.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="73abafc8-26fa-4248-b877-149ea3c0fd29">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>7.38 43.04 0.0 0.0 43.04 0.0 0.0 43.04 16.1 7.38 43.04 16.1 7.38 43.04 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b8f54f89-a706-4d81-8d0a-368e963cf873">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 43.04 0.0 0.0 40.0 0.0 0.0 40.0 16.1 0.0 43.04 16.1 0.0 43.04 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="19bb955a-2ed0-4e7a-8f5c-e4b847c8ab7b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>7.38 40.0 0.0 7.38 43.04 0.0 7.38 43.04 16.1 7.38 40.0 16.1 7.38 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="95d48547-0a3a-44ad-aaa3-b4632199ce47">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 0.0 0.0 43.04 0.0 7.38 43.04 0.0 7.38 40.0 0.0 0.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="0c966417-a6fa-43dc-8c5d-60281cdec96c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 40.0 16.1 7.38 40.0 16.1 7.38 43.04 16.1 0.0 43.04 16.1 0.0 40.0 16.1</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="580bc1f5-b498-4048-a45b-e65a9d18c75a">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1990</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="2ced6cca-aa15-4095-9bf5-08157d346bb4">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 60.0 0.0 9.27 60.0 0.0 9.27 60.0 7.42 0.0 60.0 7.42 0.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="bb159a8f-d7de-4621-9748-95fb2e0f3e2e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>9.27 63.37 0.0 0.0 63.37 0.0 0.0 63.37 7.42 9.27 63.37 7.42 9.27 63.37 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="412a7083-1c03-4b8d-9706-da5cac067452">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 63.37 0.0 0.0 60.0 0.0 0.0 60.0 7.42 0.0 63.37 7.42 0.0 63.37 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b083c091-3334-4340-86e2-696e61a4a44e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>9.27 60.0 0.0 9.27 63.37 0.0 9.27 63.37 7.42 9.27 60.0 7.42 9.27 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="d097db8b-088e-47f0-aefb-42534d17e7e6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 60.0 0.0 0.0 63.37 0.0 9.27 63.37 0.0 9.27 60.0 0.0 0.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="e98f23c2-7567-4ee7-9c4c-8132ff8ca8e2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 60.0 7.42 9.27 60.0 7.42 9.27 63.37 7.42 0.0 63.37 7.42 0.0 60.0 7.42</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="95a4abfb-cd95-422f-9c27-ebea911dcc4f">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1967</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="88697a6d-1091-4fdb-bb2f-ce810c0de3bf">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 0.0 23.990000000000002 0.0 0.0 23.990000000000002 0.0 10.206002506265664 20.0 0.0 10.206002506265664 20.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="354ba9be-f3a6-4188-ae31-c8ec66d884a8">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.990000000000002 5.74 0.0 20.0 5.74 0.0 20.0 5.74 10.206002506265664 23.990000000000002 5.74 10.206002506265664 23.990000000000002 5.74 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2ed56afa-5570-41e0-881b-4cc4ea1964e3">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 5.74 0.0 20.0 0.0 0.0 20.0 0.0 10.206002506265664 20.0 5.74 10.206002506265664 20.0 5.74 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="5ae02b6f-a682-4998-af78-a0c26322fa22">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.990000000000002 0.0 0.0 23.990000000000002 5.74 0.0 23.990000000000002 5.74 10.206002506265664 23.990000000000002 0.0 10.206002506265664 23.990000000000002 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="7a623108-fc47-4943-978c-9c2eeff4a5fc">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 0.0 20.0 5.74 0.0 23.990000000000002 5.74 0.0 23.990000000000002 0.0 0.0 20.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="bc38cbc6-d364-4ddf-9505-ac6a7af63a3a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 0.0 10.206002506265664 23.990000000000002 0.0 10.206002506265664 23.990000000000002 5.74 10.206002506265664 20.0 5.74 10.206002506265664 20.0 0.0 10.206002506265664</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="3d5dea93-0b71-41ff-b5f5-438bad25f186">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1959</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="c51a402e-376d-46e3-a191-45e0dc029c8b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 0.0 23.11 20.0 0.0 23.11 20.0 10.457604501607719 20.0 20.0 10.457604501607719 20.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="47809c0f-9525-4307-9cb2-2ec5ee4e4a31">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.11 28.83 0.0 20.0 28.83 0.0 20.0 28.83 10.457604501607719 23.11 28.83 10.457604501607719 23.11 28.83 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="3ab8f2d3-c505-44be-be62-897b4eec844c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 28.83 0.0 20.0 20.0 0.0 20.0 20.0 10.457604501607719 20.0 28.83 10.457604501607719 20.0 28.83 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="496bc642-bf61-4170-a6f4-30b05cc01d6a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.11 20.0 0.0 23.11 28.83 0.0 23.11 28.83 10.457604501607719 23.11 20.0 10.457604501607719 23.11 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="0ff0f31b-bfe6-408e-af9c-e5e61d1bd32c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 0.0 20.0 28.83 0.0 23.11 28.83 0.0 23.11 20.0 0.0 20.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="28eb993d-f7ec-4ca9-97d3-89435b274ead">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 20.0 10.457604501607719 23.11 20.0 10.457604501607719 23.11 28.83 10.457604501607719 20.0 28.83 10.457604501607719 20.0 20.0 10.457604501607719</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="60bc0619-7b36-44bd-ae91-da3c4563c587">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1948</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="e1d39809-85ad-4749-b351-d3cd46238e2c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 0.0 23.16 40.0 0.0 23.16 40.0 10.92 20.0 40.0 10.92 20.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="9dc0375a-c5c6-4e9c-9bfa-1a291c6ed405">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.16 48.730000000000004 0.0 20.0 48.730000000000004 0.0 20.0 48.730000000000004 10.92 23.16 48.730000000000004 10.92 23.16 48.730000000000004 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="5d2f3308-3d86-4b85-a323-a04d4070b50f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 48.730000000000004 0.0 20.0 40.0 0.0 20.0 40.0 10.92 20.0 48.730000000000004 10.92 20.0 48.730000000000004 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="76fb361b-0a9d-48c6-abe7-d06ea7bbfb13">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>23.16 40.0 0.0 23.16 48.730000000000004 0.0 23.16 48.730000000000004 10.92 23.16 40.0 10.92 23.16 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="d65c56c1-c193-43ba-bb07-fed5becdf3ac">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 0.0 20.0 48.730000000000004 0.0 23.16 48.730000000000004 0.0 23.16 40.0 0.0 20.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="822401cd-40d9-4c5c-be5a-b5ff96907427">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 40.0 10.92 23.16 40.0 10.92 23.16 48.730000000000004 10.92 20.0 48.730000000000004 10.92 20.0 40.0 10.92</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="d333dfad-c0a0-4cad-8565-a93c5e17ce8d">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>2009</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="c8921148-a8bf-4601-ba9d-0caabe124612">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 60.0 0.0 28.36 60.0 0.0 28.36 60.0 6.8 20.0 60.0 6.8 20.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="00c32675-d801-40ed-a8d4-6a74d77153fe">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>28.36 64.12 0.0 20.0 64.12 0.0 20.0 64.12 6.8 28.36 64.12 6.8 28.36 64.12 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="fbce51a1-4e0d-4401-95f6-1eb838a08851">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 64.12 0.0 20.0 60.0 0.0 20.0 60.0 6.8 20.0 64.12 6.8 20.0 64.12 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ea99a138-ab3f-47b9-9fe8-1b6992bb4272">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>28.36 60.0 0.0 28.36 64.12 0.0 28.36 64.12 6.8 28.36 60.0 6.8 28.36 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="5eb6dcdc-1878-42c8-8b66-f9ceceb94594">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 60.0 0.0 20.0 64.12 0.0 28.36 64.12 0.0 28.36 60.0 0.0 20.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b84c6dd6-06e4-4c2d-addd-cc822625daa0">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>20.0 60.0 6.8 28.36 60.0 6.8 28.36 64.12 6.8 20.0 64.12 6.8 20.0 60.0 6.8</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="fcbb6855-ac3c-4a96-97b2-4a33bbfeede9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="758af7ba-c247-42c9-8d4c-4b138444e61e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 0.0 46.08 0.0 0.0 46.08 0.0 11.337631578947368 40.0 0.0 11.337631578947368 40.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c66a7135-f9eb-406e-8f56-f7508a5f286a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.08 7.35 0.0 40.0 7.35 0.0 40.0 7.35 11.337631578947368 46.08 7.35 11.337631578947368 46.08 7.35 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b321ffbb-3cec-46d0-9e74-7612005fe161">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 7.35 0.0 40.0 0.0 0.0 40.0 0.0 11.337631578947368 40.0 7.35 11.337631578947368 40.0 7.35 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="e56ad592-ed0f-4745-a94d-dd1c16c2b51d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.08 0.0 0.0 46.08 7.35 0.0 46.08 7.35 11.337631578947368 46.08 0.0 11.337631578947368 46.08 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="118dff4c-122f-4a20-a974-f542bd5b1977">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 0.0 40.0 7.35 0.0 46.08 7.35 0.0 46.08 0.0 0.0 40.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="934dedba-7722-494e-9ef3-39c5e118def1">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 0.0 11.337631578947368 46.08 0.0 11.337631578947368 46.08 7.35 11.337631578947368 40.0 7.35 11.337631578947368 40.0 0.0 11.337631578947368</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="ba98e18f-aa5d-4a9d-8aaf-3f21da173020">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1947</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="f4ba4cbf-f075-44b5-a319-701f71df9bd9">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 0.0 46.730000000000004 20.0 0.0 46.730000000000004 20.0 6.7 40.0 20.0 6.7 40.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="d5781e6a-41c2-4153-adfd-35c23d0c3f17">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.730000000000004 29.14 0.0 40.0 29.14 0.0 40.0 29.14 6.7 46.730000000000004 29.14 6.7 46.730000000000004 29.14 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="8bd5f7de-ab0a-4391-902c-a531bfcf4c0a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 29.14 0.0 40.0 20.0 0.0 40.0 20.0 6.7 40.0 29.14 6.7 40.0 29.14 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="fd48339b-d02d-4233-8417-2f82add267c2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>46.730000000000004 20.0 0.0 46.730000000000004 29.14 0.0 46.730000000000004 29.14 6.7 46.730000000000004 20.0 6.7 46.730000000000004 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="521e8c9c-06fc-4fc1-b0db-d906e9a951bd">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 0.0 40.0 29.14 0.0 46.730000000000004 29.14 0.0 46.730000000000004 20.0 0.0 40.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="18647800-7c77-4dd1-97f7-ad14d821bc7a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 20.0 6.7 46.730000000000004 20.0 6.7 46.730000000000004 29.14 6.7 40.0 29.14 6.7 40.0 20.0 6.7</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="b6d27324-c418-4f19-9c31-45eebddc6300">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1982</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="ea03e9f4-4ef7-45e1-8569-3a6b4ec147a5">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 0.0 47.44 40.0 0.0 47.44 40.0 13.36 40.0 40.0 13.36 40.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="92f52a15-971d-42d1-8544-03d285fcaf45">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>47.44 45.5 0.0 40.0 45.5 0.0 40.0 45.5 13.36 47.44 45.5 13.36 47.44 45.5 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="acc75b72-82cc-4892-a6ed-1e7e21a15abe">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 45.5 0.0 40.0 40.0 0.0 40.0 40.0 13.36 40.0 45.5 13.36 40.0 45.5 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="6ac914e0-7d16-4609-88de-56f6c59a41a2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>47.44 40.0 0.0 47.44 45.5 0.0 47.44 45.5 13.36 47.44 40.0 13.36 47.44 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="47c8701c-ca9c-46b1-ac6b-db2c8cb346a2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 0.0 40.0 45.5 0.0 47.44 45.5 0.0 47.44 40.0 0.0 40.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="1e59070d-39c2-461c-949f-dd4ad54fd425">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 40.0 13.36 47.44 40.0 13.36 47.44 45.5 13.36 40.0 45.5 13.36 40.0 40.0 13.36</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45162044-732c-4d1b-9ee7-877f1376456e">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1989</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="4a99c258-7c4a-4a90-86ed-4b1525d9d5ad">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 60.0 0.0 43.07 60.0 0.0 43.07 60.0 12.4 40.0 60.0 12.4 40.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="cecc4eae-aae8-46e5-a4e7-d8e2eb177195">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>43.07 67.81 0.0 40.0 67.81 0.0 40.0 67.81 12.4 43.07 67.81 12.4 43.07 67.81 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="d8143cc4-d33d-4c98-9ce7-c5c6134ec200">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 67.81 0.0 40.0 60.0 0.0 40.0 60.0 12.4 40.0 67.81 12.4 40.0 67.81 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a7e44645-0733-47b2-a1b4-3b73626d0e24">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>43.07 60.0 0.0 43.07 67.81 0.0 43.07 67.81 12.4 43.07 60.0 12.4 43.07 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="6c716fa1-fcfb-4f99-a9e2-7ac2844aff61">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 60.0 0.0 40.0 67.81 0.0 43.07 67.81 0.0 43.07 60.0 0.0 40.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b91bf595-7f5b-4e41-9d4b-b8ce6ae46ffb">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>40.0 60.0 12.4 43.07 60.0 12.4 43.07 67.81 12.4 40.0 67.81 12.4 40.0 60.0 12.4</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6eb5dd57-e0d2-4de1-8989-e3622fde68f0">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="d17267b2-ca46-4050-9c3c-4ea15982f352">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 69.18 0.0 0.0 69.18 0.0 4.52 60.0 0.0 4.52 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="8e1dfaf9-908b-4562-b05d-9fa9ea9df8bc">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>69.18 5.06 0.0 60.0 5.06 0.0 60.0 5.06 4.52 69.18 5.06 4.52 69.18 5.06 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="35e00cf1-00e5-442b-ba93-22bc09708f9c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 5.06 0.0 60.0 0.0 0.0 60.0 0.0 4.52 60.0 5.06 4.52 60.0 5.06 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="2cf2cbc8-fb4f-4a67-8fe8-ab04178f148b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>69.18 0.0 0.0 69.18 5.06 0.0 69.18 5.06 4.52 69.18 0.0 4.52 69.18 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c41f5acd-0c01-4687-8aa4-0edb9f1505d1">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 0.0 60.0 5.06 0.0 69.18 5.06 0.0 69.18 0.0 0.0 60.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ff902ddc-e1be-41f6-8c47-47e6bad52953">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 0.0 4.52 69.18 0.0 4.52 69.18 5.06 4.52 60.0 5.06 4.52 60.0 0.0 4.52</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45d9f60d-0834-41d0-9844-5b92fb1b72a9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1974</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="96f98f5d-a0e8-40f1-a990-4262fb97c7b6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 20.0 0.0 63.38 20.0 0.0 63.38 20.0 4.4592307692307696 60.0 20.0 4.4592307692307696 60.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b56f4f5e-da2c-4af7-9bf7-048b5d1eba9c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.38 27.17 0.0 60.0 27.17 0.0 60.0 27.17 4.4592307692307696 63.38 27.17 4.4592307692307696 63.38 27.17 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="7869d3c7-5b55-4015-a52b-0ada4536fe0a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 27.17 0.0 60.0 20.0 0.0 60.0 20.0 4.4592307692307696 60.0 27.17 4.4592307692307696 60.0 27.17 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="7f4cdd49-34ff-4229-97e8-723ec76f5679">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.38 20.0 0.0 63.38 27.17 0.0 63.38 27.17 4.4592307692307696 63.38 20.0 4.4592307692307696 63.38 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="6ca67336-7716-4738-98c3-4f97c9f4e364">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 20.0 0.0 60.0 27.17 0.0 63.38 27.17 0.0 63.38 20.0 0.0 60.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="668a6e91-4bf2-491b-adda-c0172bfa6834">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 20.0 4.4592307692307696 63.38 20.0 4.4592307692307696 63.38 27.17 4.4592307692307696 60.0 27.17 4.4592307692307696 60.0 20.0 4.4592307692307696</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="555175a2-22c2-41a7-b85f-2fb869fc519b">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="496c0d6b-1a23-4223-90e4-c19481bbbd29">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 40.0 0.0 63.05 40.0 0.0 63.05 40.0 4.42 60.0 40.0 4.42 60.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a8da92d6-feb1-4bc1-b72c-9810a2afe94b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.05 45.29 0.0 60.0 45.29 0.0 60.0 45.29 4.42 63.05 45.29 4.42 63.05 45.29 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="9651173b-d6a3-4206-9fd0-13d0bfd27cea">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 45.29 0.0 60.0 40.0 0.0 60.0 40.0 4.42 60.0 45.29 4.42 60.0 45.29 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="8d8a37cc-c19f-41d5-85a8-2b7c622a5def">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.05 40.0 0.0 63.05 45.29 0.0 63.05 45.29 4.42 63.05 40.0 4.42 63.05 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="1f36a5ef-e7ad-4ca9-b350-433f28597c47">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 40.0 0.0 60.0 45.29 0.0 63.05 45.29 0.0 63.05 40.0 0.0 60.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="da6284b5-5faf-4202-a015-0e665b984310">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 40.0 4.42 63.05 40.0 4.42 63.05 45.29 4.42 60.0 45.29 4.42 60.0 40.0 4.42</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="32ef008b-6848-4e06-ad57-2cec22eeb093">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="917ecdca-b6d3-4dd9-bb3e-6017366ddece">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 60.0 0.0 63.76 60.0 0.0 63.76 60.0 13.6 60.0 60.0 13.6 60.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="fc7fbe99-c3de-497a-8b7c-b6d9f5bda1c4">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.76 63.72 0.0 60.0 63.72 0.0 60.0 63.72 13.6 63.76 63.72 13.6 63.76 63.72 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="e375873e-e170-4e65-b817-80a552c95fdb">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 63.72 0.0 60.0 60.0 0.0 60.0 60.0 13.6 60.0 63.72 13.6 60.0 63.72 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="7ca8bbd9-2edd-4e01-93da-d5580f7c0e9c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>63.76 60.0 0.0 63.76 63.72 0.0 63.76 63.72 13.6 63.76 60.0 13.6 63.76 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="06d76cab-9734-49ba-a170-5790f6e6493d">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 60.0 0.0 60.0 63.72 0.0 63.76 63.72 0.0 63.76 60.0 0.0 60.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="159c0b84-333e-44bc-94c6-729887aceb8f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>60.0 60.0 13.6 63.76 60.0 13.6 63.76 63.72 13.6 60.0 63.72 13.6 60.0 60.0 13.6</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="a64f3754-2a76-4790-ad49-598f014e6814">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="87a8abe0-9243-4d43-a67b-8957b25c610a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 0.0 0.0 84.39 0.0 0.0 84.39 0.0 14.0 80.0 0.0 14.0 80.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="b62407e8-9c53-4725-aa93-c8757657de21">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>84.39 9.8 0.0 80.0 9.8 0.0 80.0 9.8 14.0 84.39 9.8 14.0 84.39 9.8 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="83040546-d3d6-4c46-9878-62af1f9cc0ea">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 9.8 0.0 80.0 0.0 0.0 80.0 0.0 14.0 80.0 9.8 14.0 80.0 9.8 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c59b6ab2-4927-4e42-a352-9cfbbf4b8a51">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>84.39 0.0 0.0 84.39 9.8 0.0 84.39 9.8 14.0 84.39 0.0 14.0 84.39 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a0296b31-ff23-46d7-8ae5-7137eb2c9aba">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 0.0 0.0 80.0 9.8 0.0 84.39 9.8 0.0 84.39 0.0 0.0 80.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="3e4c8958-829e-47b1-83b2-b65354664c3e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 0.0 14.0 84.39 0.0 14.0 84.39 9.8 14.0 80.0 9.8 14.0 80.0 0.0 14.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="4e73a2b8-54cc-4722-a8b8-57971461b270">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1952</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="53f412e9-fba6-47cf-a39e-ac156924b4fd">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 20.0 0.0 85.27 20.0 0.0 85.27 20.0 8.155 80.0 20.0 8.155 80.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="a182b599-1cdb-4ac9-aea4-c008672bb043">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>85.27 24.13 0.0 80.0 24.13 0.0 80.0 24.13 8.155 85.27 24.13 8.155 85.27 24.13 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="e9da80e4-127d-4330-b024-26a6d6ad9ba2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 24.13 0.0 80.0 20.0 0.0 80.0 20.0 8.155 80.0 24.13 8.155 80.0 24.13 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="95be99fd-b92e-4bbf-b46a-f12667ab7208">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>85.27 20.0 0.0 85.27 24.13 0.0 85.27 24.13 8.155 85.27 20.0 8.155 85.27 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="ec99be8d-a4e4-4cdd-8153-5970f55a5543">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 20.0 0.0 80.0 24.13 0.0 85.27 24.13 0.0 85.27 20.0 0.0 80.0 20.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c3480509-2cd8-4798-8c27-0850818e734e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 20.0 8.155 85.27 20.0 8.155 85.27 24.13 8.155 80.0 24.13 8.155 80.0 20.0 8.155</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="44e2c197-1881-4ec3-bc14-f284bfa8716c">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="1a2b4071-345f-492b-8f4e-4998c0d27dee">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 40.0 0.0 83.52 40.0 0.0 83.52 40.0 15.5 80.0 40.0 15.5 80.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f8d44085-551f-44bb-aa7b-b08f909ba801">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>83.52 49.62 0.0 80.0 49.62 0.0 80.0 49.62 15.5 83.52 49.62 15.5 83.52 49.62 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="c9f48b5e-8042-43ec-9db0-2fb940ff4353">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 49.62 0.0 80.0 40.0 0.0 80.0 40.0 15.5 80.0 49.62 15.5 80.0 49.62 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="3991e61b-cc55-4382-828c-bbd81ee6b8db">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>83.52 40.0 0.0 83.52 49.62 0.0 83.52 49.62 15.5 83.52 40.0 15.5 83.52 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="982ebcdd-63b3-415d-820c-86fbcc36cca2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 40.0 0.0 80.0 49.62 0.0 83.52 49.62 0.0 83.52 40.0 0.0 80.0 40.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="94d659e5-4e3a-4d75-bf0e-49d08de8b173">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 40.0 15.5 83.52 40.0 15.5 83.52 49.62 15.5 80.0 49.62 15.5 80.0 40.0 15.5</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="708daa94-e4a5-413b-8efb-3d9bc59e9f58">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="7d1f7b61-670a-44e1-a9c2-3447613da147">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 60.0 0.0 83.91 60.0 0.0 83.91 60.0 10.005588235294118 80.0 60.0 10.005588235294118 80.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="0a327b11-ca6a-4e5e-bd6c-939fff11a445">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>83.91 68.25 0.0 80.0 68.25 0.0 80.0 68.25 10.005588235294118 83.91 68.25 10.005588235294118 83.91 68.25 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="df8c8ed1-cbd2-4d58-8f26-106daf094013">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 68.25 0.0 80.0 60.0 0.0 80.0 60.0 10.005588235294118 80.0 68.25 10.005588235294118 80.0 68.25 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="81397de9-fed5-40be-ac91-868ca1fb646e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>83.91 60.0 0.0 83.91 68.25 0.0 83.91 68.25 10.005588235294118 83.91 60.0 10.005588235294118 83.91 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="1e67a24f-5410-413c-8d93-6647ce99efcd">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 60.0 0.0 80.0 68.25 0.0 83.91 68.25 0.0 83.91 60.0 0.0 80.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
            <gml:Polygon gml:id="f0febd32-b9ab-4d1e-8db3-0d4907f696c7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>80.0 60.0 10.005588235294118 83.91 60.0 10.005588235294118 83.91 68.25 10.005588235294118 80.0 68.25 10.005588235294118 80.0 60.0 10.005588235294118</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod1MultiSurface>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
