<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns="http://www.opengis.net/citygml/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:fme="http://www.safe.com/xml/xmltables">
  <gml:name>LOD2_1_F0</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="9fd16237-61d1-494c-b265-4e51b42046ed">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1969</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e3251aca-d5fc-4e8c-90e6-064dd5c5a669">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 0.0 0.0 0.0 7.77 0.0 3.34 7.77 0.0 3.34 0.0 0.0 0.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="37cc50e6-affd-477d-a777-81ab1b33c40a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 0.0 17.45 3.34 0.0 17.45 3.34 7.77 17.45 0.0 7.77 17.45 0.0 0.0 17.45</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f68daf21-adfe-4122-9fe2-e5e58ed264a6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 0.0 0.0 3.34 0.0 0.0 3.34 0.0 17.45 0.0 0.0 17.45 0.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fc04e150-cf3f-4350-a0ce-237d7546a65b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>3.34 0.0 0.0 3.34 7.77 0.0 3.34 7.77 17.45 3.34 0.0 17.45 3.34 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="79dda32e-8c35-42d2-a3b4-5537be5d9f98">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>3.34 7.77 0.0 0.0 7.77 0.0 0.0 7.77 17.45 3.34 7.77 17.45 3.34 7.77 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7258ff89-3a07-4f3a-a8bd-e7d70c176d81">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 7.77 0.0 0.0 0.0 0.0 0.0 0.0 17.45 0.0 7.77 17.45 0.0 7.77 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6e58349d-cbc4-4c44-95e6-5e550d5d0899">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9568828a-6218-4b49-bda7-1a5ff4b2ca43">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 20.0 0.0 0.0 29.6 0.0 5.72 29.6 0.0 5.72 20.0 0.0 0.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4299fa65-ec4f-4337-8a60-47fe3e81ff3a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 29.6 6.07 0.0 20.0 6.07 5.72 20.0 3.27 5.72 29.6 3.27 0.0 29.6 6.07</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9eda1176-8141-48ca-9fc1-8a9043f1e6fd">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 20.0 6.07 0.0 20.0 0.0 5.72 20.0 0.0 5.72 20.0 3.27 0.0 20.0 6.07</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a19e1bb1-74d0-4c94-81a2-675ac9eb45b8">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>5.72 20.0 0.0 5.72 29.6 0.0 5.72 29.6 3.27 5.72 20.0 3.27 5.72 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="10f975e2-043b-465e-bfc5-613b8d50d457">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>5.72 29.6 3.27 5.72 29.6 0.0 0.0 29.6 0.0 0.0 29.6 6.07 5.72 29.6 3.27</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="eb6096f1-8ecb-4ee3-8d34-2f66cca612b8">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 29.6 6.07 0.0 29.6 0.0 0.0 20.0 0.0 0.0 20.0 6.07 0.0 29.6 6.07</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="92a9ffcc-a809-436b-ab8f-213341025556">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1965</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="658d7f60-3dbd-4a2a-b46c-5a5a899051ea">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 40.0 0.0 0.0 43.04 0.0 7.38 43.04 0.0 7.38 40.0 0.0 0.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d175dff0-0143-4c40-b8e7-e5f286cefbd2">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 40.0 16.1 7.38 40.0 16.1 7.38 43.04 16.1 0.0 43.04 16.1 0.0 40.0 16.1</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="cf2ad481-2c55-40c2-b3e7-e91622f0165f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 40.0 0.0 7.38 40.0 0.0 7.38 40.0 16.1 0.0 40.0 16.1 0.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6bd69b3b-2fc6-4d12-bae5-50290f3393b5">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>7.38 40.0 0.0 7.38 43.04 0.0 7.38 43.04 16.1 7.38 40.0 16.1 7.38 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="34314ef3-743c-4248-8819-56d3fdcda738">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>7.38 43.04 0.0 0.0 43.04 0.0 0.0 43.04 16.1 7.38 43.04 16.1 7.38 43.04 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="69bfc248-dd5b-49ab-9031-3abbb84bb669">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 43.04 0.0 0.0 40.0 0.0 0.0 40.0 16.1 0.0 43.04 16.1 0.0 43.04 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="580bc1f5-b498-4048-a45b-e65a9d18c75a">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1990</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fc8dda15-b8e4-493d-970b-7f746790dc10">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 60.0 0.0 0.0 63.37 0.0 9.27 63.37 0.0 9.27 60.0 0.0 0.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2725542d-d607-4911-ac68-2a55aecdd62e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 63.37 8.66 0.0 60.0 8.66 9.27 60.0 6.18 9.27 63.37 6.18 0.0 63.37 8.66</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="620abb5d-f5ac-429d-980d-ea6585e428f2">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 60.0 8.66 0.0 60.0 0.0 9.27 60.0 0.0 9.27 60.0 6.18 0.0 60.0 8.66</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4a7a1f41-b5ed-43bb-8a1b-51848953bf2c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>9.27 60.0 0.0 9.27 63.37 0.0 9.27 63.37 6.18 9.27 60.0 6.18 9.27 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="12efd2d0-53a0-4404-98db-70cb1c54e61a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>9.27 63.37 6.18 9.27 63.37 0.0 0.0 63.37 0.0 0.0 63.37 8.66 9.27 63.37 6.18</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="07823a8e-b62b-4e10-8e15-8d604a5551e3">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 63.37 8.66 0.0 63.37 0.0 0.0 60.0 0.0 0.0 60.0 8.66 0.0 63.37 8.66</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="95a4abfb-cd95-422f-9c27-ebea911dcc4f">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1967</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="bfa92bc3-f967-4a87-afb2-bc4bb36714dc">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 0.0 0.0 20.0 5.74 0.0 23.990000000000002 5.74 0.0 23.990000000000002 0.0 0.0 20.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="498b950e-5c15-4dc2-b5ab-7dad66bcb27e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.995 2.09 11.379999999999999 21.995 3.6500000000000004 11.379999999999999 20.0 5.74 9.33 20.0 0.0 9.33 21.995 2.09 11.379999999999999</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6122a8fc-9878-46e1-ac02-71e64f577647">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.995 3.6500000000000004 11.379999999999999 21.995 2.09 11.379999999999999 23.990000000000002 0.0 9.33 23.990000000000002 5.74 9.33 21.995 3.6500000000000004 11.379999999999999</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4c0b9c47-a493-4586-baaf-97a75eba3d50">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.995 2.09 11.379999999999999 20.0 0.0 9.33 23.990000000000002 0.0 9.33 21.995 2.09 11.379999999999999</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="bef69ecc-1fd6-4819-9116-defa111e52d0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.995 3.6500000000000004 11.379999999999999 23.990000000000002 5.74 9.33 20.0 5.74 9.33 21.995 3.6500000000000004 11.379999999999999</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4df00264-b72c-43ed-b2ec-6add0190bb57">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 0.0 0.0 23.990000000000002 0.0 0.0 23.990000000000002 0.0 9.33 20.0 0.0 9.33 20.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c5b52001-5279-42d2-b953-1ceedd7ec3aa">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.990000000000002 0.0 0.0 23.990000000000002 5.74 0.0 23.990000000000002 5.74 9.33 23.990000000000002 0.0 9.33 23.990000000000002 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9f38cf6a-314f-4a8b-9338-904a2337550a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.990000000000002 5.74 0.0 20.0 5.74 0.0 20.0 5.74 9.33 23.990000000000002 5.74 9.33 23.990000000000002 5.74 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="42fe639f-5d6a-417b-bf48-0f5eb91f1eda">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 5.74 0.0 20.0 0.0 0.0 20.0 0.0 9.33 20.0 5.74 9.33 20.0 5.74 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="3d5dea93-0b71-41ff-b5f5-438bad25f186">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1959</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="33f11009-62f7-45c1-b9d4-3b83d33808a4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 20.0 0.0 20.0 28.83 0.0 23.11 28.83 0.0 23.11 20.0 0.0 20.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1a070e89-8ae5-443e-aabe-b33eba73cfbf">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.555 21.57 11.72 21.555 27.259999999999998 11.72 20.0 28.83 9.39 20.0 20.0 9.39 21.555 21.57 11.72</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e6d38a6c-12c7-4c1f-907a-9b89c4273468">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.555 27.259999999999998 11.72 21.555 21.57 11.72 23.11 20.0 9.39 23.11 28.83 9.39 21.555 27.259999999999998 11.72</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ea98f280-0437-4e42-a492-ea7074b19761">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.555 21.57 11.72 20.0 20.0 9.39 23.11 20.0 9.39 21.555 21.57 11.72</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="95f64f65-6f91-4842-9b72-7f37e734f519">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.555 27.259999999999998 11.72 23.11 28.83 9.39 20.0 28.83 9.39 21.555 27.259999999999998 11.72</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="08f17cad-0c3c-4af7-a867-cfc984757e91">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 20.0 0.0 23.11 20.0 0.0 23.11 20.0 9.39 20.0 20.0 9.39 20.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="10bf4885-ce81-4c2f-a7df-0bac6bd3f11a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.11 20.0 0.0 23.11 28.83 0.0 23.11 28.83 9.39 23.11 20.0 9.39 23.11 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="98db53e2-9914-43f4-90d0-4f87284e7576">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.11 28.83 0.0 20.0 28.83 0.0 20.0 28.83 9.39 23.11 28.83 9.39 23.11 28.83 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a8ded5a4-a2b7-43b9-b0b1-21de9cb7e101">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 28.83 0.0 20.0 20.0 0.0 20.0 20.0 9.39 20.0 28.83 9.39 20.0 28.83 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="60bc0619-7b36-44bd-ae91-da3c4563c587">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1948</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="35e79992-f1de-47e7-9bc9-96ff5245a59d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 40.0 0.0 20.0 48.730000000000004 0.0 23.16 48.730000000000004 0.0 23.16 40.0 0.0 20.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="96fe38bc-8081-4069-87b1-ae3f27574f84">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 48.730000000000004 11.940000000000001 20.0 40.0 11.940000000000001 23.16 40.0 9.9 23.16 48.730000000000004 9.9 20.0 48.730000000000004 11.940000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ab04c813-e6be-4e41-a5c5-a1c38bac6954">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 40.0 11.940000000000001 20.0 40.0 0.0 23.16 40.0 0.0 23.16 40.0 9.9 20.0 40.0 11.940000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b542cdd3-c9a5-4e99-8b10-0ced934434e6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.16 40.0 0.0 23.16 48.730000000000004 0.0 23.16 48.730000000000004 9.9 23.16 40.0 9.9 23.16 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fa6b78cb-739f-400c-aa73-317c2516eaf1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.16 48.730000000000004 9.9 23.16 48.730000000000004 0.0 20.0 48.730000000000004 0.0 20.0 48.730000000000004 11.940000000000001 23.16 48.730000000000004 9.9</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d249e8ed-1615-4319-8778-488dd9c2e2c7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 48.730000000000004 11.940000000000001 20.0 48.730000000000004 0.0 20.0 40.0 0.0 20.0 40.0 11.940000000000001 20.0 48.730000000000004 11.940000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="d333dfad-c0a0-4cad-8565-a93c5e17ce8d">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>2009</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5e463ef0-1c56-4a1f-9c57-132599bfa962">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 60.0 0.0 20.0 64.12 0.0 28.36 64.12 0.0 28.36 60.0 0.0 20.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d03bacaf-acd2-4487-b008-955e4a2c1ea2">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 60.0 6.8 28.36 60.0 6.8 28.36 64.12 6.8 20.0 64.12 6.8 20.0 60.0 6.8</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9dead698-4bec-4d82-a70f-423cfe9b0c96">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 60.0 0.0 28.36 60.0 0.0 28.36 60.0 6.8 20.0 60.0 6.8 20.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4e444535-c1d7-4611-8e47-696e1dc62288">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>28.36 60.0 0.0 28.36 64.12 0.0 28.36 64.12 6.8 28.36 60.0 6.8 28.36 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="79dbd659-581f-42eb-bf2c-bece822b29d1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>28.36 64.12 0.0 20.0 64.12 0.0 20.0 64.12 6.8 28.36 64.12 6.8 28.36 64.12 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="36c0d1e8-8876-4762-b683-4f4c55da32d7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 64.12 0.0 20.0 60.0 0.0 20.0 60.0 6.8 20.0 64.12 6.8 20.0 64.12 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="fcbb6855-ac3c-4a96-97b2-4a33bbfeede9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e65e2d64-e4c0-418f-90e5-541a95a73c20">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 0.0 0.0 40.0 7.35 0.0 46.08 7.35 0.0 46.08 0.0 0.0 40.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b28c6d1b-096a-4004-8edf-5e6bd0d9fd26">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>43.04 0.0 13.620000000000001 43.04 7.35 13.620000000000001 40.0 7.35 10.08 40.0 0.0 10.08 43.04 0.0 13.620000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fbf051f3-a813-43c3-9608-0297c67e01ba">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>43.04 7.35 13.620000000000001 43.04 0.0 13.620000000000001 46.08 0.0 10.08 46.08 7.35 10.08 43.04 7.35 13.620000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2ea06cbe-6daf-4d59-a79b-213a647300a7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 0.0 10.08 40.0 0.0 0.0 46.08 0.0 0.0 46.08 0.0 10.08 43.04 0.0 13.620000000000001 40.0 0.0 10.08</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ae1b159f-0623-49f7-ab99-ae75e83ed9c5">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.08 0.0 0.0 46.08 7.35 0.0 46.08 7.35 10.08 46.08 0.0 10.08 46.08 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="be0603a6-650c-4094-8e2b-0063b135cf41">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.08 7.35 10.08 46.08 7.35 0.0 40.0 7.35 0.0 40.0 7.35 10.08 43.04 7.35 13.620000000000001 46.08 7.35 10.08</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e63b1a85-7ccb-470f-8498-7983e6f0420f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 7.35 10.08 40.0 7.35 0.0 40.0 0.0 0.0 40.0 0.0 10.08 40.0 7.35 10.08</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="ba98e18f-aa5d-4a9d-8aaf-3f21da173020">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1947</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="243ef7e5-8bdc-4007-99bd-4e9d288b4817">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 20.0 0.0 40.0 29.14 0.0 46.730000000000004 29.14 0.0 46.730000000000004 20.0 0.0 40.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="82625ff6-b5d4-4da8-a44c-844c5a4dd45e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 20.0 6.7 46.730000000000004 20.0 6.7 46.730000000000004 29.14 6.7 40.0 29.14 6.7 40.0 20.0 6.7</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="26046498-c8ba-448b-85f9-75cfb9890808">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 20.0 0.0 46.730000000000004 20.0 0.0 46.730000000000004 20.0 6.7 40.0 20.0 6.7 40.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f18f25d3-c4c6-4ee9-8afd-331f353518ad">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.730000000000004 20.0 0.0 46.730000000000004 29.14 0.0 46.730000000000004 29.14 6.7 46.730000000000004 20.0 6.7 46.730000000000004 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1f528488-8e4e-4d9b-9005-f21356cd93bd">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.730000000000004 29.14 0.0 40.0 29.14 0.0 40.0 29.14 6.7 46.730000000000004 29.14 6.7 46.730000000000004 29.14 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e86e73d1-ce7c-4c84-8469-7e420315eeee">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 29.14 0.0 40.0 20.0 0.0 40.0 20.0 6.7 40.0 29.14 6.7 40.0 29.14 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="b6d27324-c418-4f19-9c31-45eebddc6300">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1982</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3b1b7b56-1097-4fb2-97a1-1be5fb2f52bd">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 40.0 0.0 40.0 45.5 0.0 47.44 45.5 0.0 47.44 40.0 0.0 40.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2c6abe25-4c01-45c3-9ed3-4b701236a1fc">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 40.0 13.36 47.44 40.0 13.36 47.44 45.5 13.36 40.0 45.5 13.36 40.0 40.0 13.36</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="43956acc-75fd-4c65-960b-d3532e9c32a1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 40.0 0.0 47.44 40.0 0.0 47.44 40.0 13.36 40.0 40.0 13.36 40.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ae79c4b9-c2d5-415b-991c-b12f699d3551">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>47.44 40.0 0.0 47.44 45.5 0.0 47.44 45.5 13.36 47.44 40.0 13.36 47.44 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="003a0b28-3e8b-4af9-a69a-a35c6a26af31">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>47.44 45.5 0.0 40.0 45.5 0.0 40.0 45.5 13.36 47.44 45.5 13.36 47.44 45.5 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1f397ef4-2a7b-4d43-a9c3-0ce4dc826a67">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 45.5 0.0 40.0 40.0 0.0 40.0 40.0 13.36 40.0 45.5 13.36 40.0 45.5 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45162044-732c-4d1b-9ee7-877f1376456e">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1989</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2a61cc4c-09b1-483e-8508-76e54cea9484">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 60.0 0.0 40.0 67.81 0.0 43.07 67.81 0.0 43.07 60.0 0.0 40.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="47586cb0-7930-4cb6-a7d3-84402e99e0a5">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 60.0 12.4 43.07 60.0 12.4 43.07 67.81 12.4 40.0 67.81 12.4 40.0 60.0 12.4</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3632648b-9aaf-4c05-a7cd-2800f7c77871">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 60.0 0.0 43.07 60.0 0.0 43.07 60.0 12.4 40.0 60.0 12.4 40.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="15d1fb1c-7179-4fc6-9697-1f011ef13e41">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>43.07 60.0 0.0 43.07 67.81 0.0 43.07 67.81 12.4 43.07 60.0 12.4 43.07 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2832d7cf-e520-4114-9d79-5de6f9e786ff">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>43.07 67.81 0.0 40.0 67.81 0.0 40.0 67.81 12.4 43.07 67.81 12.4 43.07 67.81 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="23da271f-7f34-407a-bfc1-11e0914fa9eb">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 67.81 0.0 40.0 60.0 0.0 40.0 60.0 12.4 40.0 67.81 12.4 40.0 67.81 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6eb5dd57-e0d2-4de1-8989-e3622fde68f0">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="aae5324d-08ff-4042-a237-96b2ab9b84bd">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 0.0 0.0 60.0 5.06 0.0 69.18 5.06 0.0 69.18 0.0 0.0 60.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d44e4b46-8ef1-44d8-ac65-838e47ea56ac">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 5.06 5.92 60.0 0.0 5.92 69.18 0.0 3.12 69.18 5.06 3.12 60.0 5.06 5.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c3ae28f3-de8e-4b26-a28e-ce4fdadce613">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 0.0 5.92 60.0 0.0 0.0 69.18 0.0 0.0 69.18 0.0 3.12 60.0 0.0 5.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="11daab30-ecd4-448a-956a-5cf80c180615">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>69.18 0.0 0.0 69.18 5.06 0.0 69.18 5.06 3.12 69.18 0.0 3.12 69.18 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="8fe4c380-5249-4e10-9e49-b4fb943c0766">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>69.18 5.06 3.12 69.18 5.06 0.0 60.0 5.06 0.0 60.0 5.06 5.92 69.18 5.06 3.12</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9d32fa58-5b7d-4f71-a39c-342e524cbec2">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 5.06 5.92 60.0 5.06 0.0 60.0 0.0 0.0 60.0 0.0 5.92 60.0 5.06 5.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45d9f60d-0834-41d0-9844-5b92fb1b72a9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1974</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="06d7fb3e-2dbf-4539-86b7-8e59549139a7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 20.0 0.0 60.0 27.17 0.0 63.38 27.17 0.0 63.38 20.0 0.0 60.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="368e1d0b-2f2a-4977-a02f-9f87e2076241">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>61.69 20.0 6.29 61.69 27.17 6.29 60.0 27.17 3.49 60.0 20.0 3.49 61.69 20.0 6.29</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="af9ff6bc-1bb8-4ca1-bf2e-42244f47ea28">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>61.69 27.17 6.29 61.69 20.0 6.29 63.38 20.0 3.49 63.38 27.17 3.49 61.69 27.17 6.29</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4b65ff29-686e-4b9e-9547-a8ef954aa246">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 20.0 3.49 60.0 20.0 0.0 63.38 20.0 0.0 63.38 20.0 3.49 61.69 20.0 6.29 60.0 20.0 3.49</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="19bf252c-6d05-4ed1-a5ba-b1a7214abda6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.38 20.0 0.0 63.38 27.17 0.0 63.38 27.17 3.49 63.38 20.0 3.49 63.38 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6242ad5f-26a4-4469-875b-c8a1878963cd">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.38 27.17 3.49 63.38 27.17 0.0 60.0 27.17 0.0 60.0 27.17 3.49 61.69 27.17 6.29 63.38 27.17 3.49</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7978d5b8-a5ac-4989-b434-82d0a0a4029f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 27.17 3.49 60.0 27.17 0.0 60.0 20.0 0.0 60.0 20.0 3.49 60.0 27.17 3.49</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="555175a2-22c2-41a7-b85f-2fb869fc519b">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="079bb91d-c130-44e7-ad52-c7dc49c99f61">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 40.0 0.0 60.0 45.29 0.0 63.05 45.29 0.0 63.05 40.0 0.0 60.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5b6febbc-38e6-4d91-83a0-10c233c8c3e6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 45.29 5.82 60.0 40.0 5.82 63.05 40.0 3.02 63.05 45.29 3.02 60.0 45.29 5.82</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2f305afd-2a36-4a3d-9cbd-3ceb15414dc1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 40.0 5.82 60.0 40.0 0.0 63.05 40.0 0.0 63.05 40.0 3.02 60.0 40.0 5.82</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6a910240-d62f-432a-a7fe-a43af56350a2">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.05 40.0 0.0 63.05 45.29 0.0 63.05 45.29 3.02 63.05 40.0 3.02 63.05 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="af6ae8f0-ef46-4c87-b3d0-6e1218baceb1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.05 45.29 3.02 63.05 45.29 0.0 60.0 45.29 0.0 60.0 45.29 5.82 63.05 45.29 3.02</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b091f05a-5ed7-4aa9-8fa2-ea4e088d2994">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 45.29 5.82 60.0 45.29 0.0 60.0 40.0 0.0 60.0 40.0 5.82 60.0 45.29 5.82</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="32ef008b-6848-4e06-ad57-2cec22eeb093">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="29391495-a0db-4239-a504-ea13c1d0a8d3">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 60.0 0.0 60.0 63.72 0.0 63.76 63.72 0.0 63.76 60.0 0.0 60.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="716b3355-b714-49a3-9d07-2a03443b6499">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 60.0 13.6 63.76 60.0 13.6 63.76 63.72 13.6 60.0 63.72 13.6 60.0 60.0 13.6</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7f27ed4b-842b-4bbe-8130-8039d24d1df7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 60.0 0.0 63.76 60.0 0.0 63.76 60.0 13.6 60.0 60.0 13.6 60.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="372bcecf-223f-421b-ac54-4fc24acf9247">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.76 60.0 0.0 63.76 63.72 0.0 63.76 63.72 13.6 63.76 60.0 13.6 63.76 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b4448d09-1a3d-40df-b064-c0d6e9502f8b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.76 63.72 0.0 60.0 63.72 0.0 60.0 63.72 13.6 63.76 63.72 13.6 63.76 63.72 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5dcfb62c-e771-4a47-8cd4-c7aeb4ba3de0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 63.72 0.0 60.0 60.0 0.0 60.0 60.0 13.6 60.0 63.72 13.6 60.0 63.72 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="a64f3754-2a76-4790-ad49-598f014e6814">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9e97731e-7d8e-4ebc-99b9-89585e568d9b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 0.0 0.0 80.0 9.8 0.0 84.39 9.8 0.0 84.39 0.0 0.0 80.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="06e0387b-26ad-4b7b-b78b-438e6f2e5082">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 0.0 14.0 84.39 0.0 14.0 84.39 9.8 14.0 80.0 9.8 14.0 80.0 0.0 14.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e74e8517-eefa-4976-b56d-09368257f45e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 0.0 0.0 84.39 0.0 0.0 84.39 0.0 14.0 80.0 0.0 14.0 80.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="61a4cc71-f506-4911-9646-b3f370520bb1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>84.39 0.0 0.0 84.39 9.8 0.0 84.39 9.8 14.0 84.39 0.0 14.0 84.39 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fe5e2a66-63d1-402a-9442-3632c4847f6f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>84.39 9.8 0.0 80.0 9.8 0.0 80.0 9.8 14.0 84.39 9.8 14.0 84.39 9.8 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d0dd8c11-66ec-4b6a-b548-422d3b898790">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 9.8 0.0 80.0 0.0 0.0 80.0 0.0 14.0 80.0 9.8 14.0 80.0 9.8 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="4e73a2b8-54cc-4722-a8b8-57971461b270">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1952</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e8230519-b2ad-4aed-8844-6d89d1151b1b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 20.0 0.0 80.0 24.13 0.0 85.27 24.13 0.0 85.27 20.0 0.0 80.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d2a9e3f1-2082-4a21-b201-1bad0182703f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 24.13 9.39 80.0 20.0 9.39 85.27 20.0 6.92 85.27 24.13 6.92 80.0 24.13 9.39</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b2636157-3900-49a5-914d-ee678097dc6d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 20.0 9.39 80.0 20.0 0.0 85.27 20.0 0.0 85.27 20.0 6.92 80.0 20.0 9.39</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1ab80c80-9a9d-4297-a536-5f1515a9c80d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>85.27 20.0 0.0 85.27 24.13 0.0 85.27 24.13 6.92 85.27 20.0 6.92 85.27 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="12caaa3b-3d1a-4291-a458-fb513059c742">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>85.27 24.13 6.92 85.27 24.13 0.0 80.0 24.13 0.0 80.0 24.13 9.39 85.27 24.13 6.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="00e72252-2081-4121-8b87-bb6ef11b7e57">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 24.13 9.39 80.0 24.13 0.0 80.0 20.0 0.0 80.0 20.0 9.39 80.0 24.13 9.39</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="44e2c197-1881-4ec3-bc14-f284bfa8716c">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="01f58a63-2db8-4ca0-9d46-34ae93cf0d7e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 40.0 0.0 80.0 49.62 0.0 83.52 49.62 0.0 83.52 40.0 0.0 80.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="604c3097-6b5a-4069-a21f-6ac2e029558d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 40.0 15.5 83.52 40.0 15.5 83.52 49.62 15.5 80.0 49.62 15.5 80.0 40.0 15.5</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6a00379b-b9fe-43b0-bfa3-077ed5034473">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 40.0 0.0 83.52 40.0 0.0 83.52 40.0 15.5 80.0 40.0 15.5 80.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f44e4553-4536-4b0e-806f-5897805cd11e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.52 40.0 0.0 83.52 49.62 0.0 83.52 49.62 15.5 83.52 40.0 15.5 83.52 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="8593313f-f705-4829-b584-2004f7ecd124">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.52 49.62 0.0 80.0 49.62 0.0 80.0 49.62 15.5 83.52 49.62 15.5 83.52 49.62 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c5a25d3c-3add-49f8-957a-d4a015a78b21">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 49.62 0.0 80.0 40.0 0.0 80.0 40.0 15.5 80.0 49.62 15.5 80.0 49.62 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="708daa94-e4a5-413b-8efb-3d9bc59e9f58">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f49cb4a2-a13c-4e60-8840-b488c4337827">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 60.0 0.0 80.0 68.25 0.0 83.91 68.25 0.0 83.91 60.0 0.0 80.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="56387bf8-9766-4ab1-9f0e-299eb57eb6e0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>81.955 61.41 11.92 81.955 66.84 11.92 80.0 68.25 9.09 80.0 60.0 9.09 81.955 61.41 11.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="bc850e2b-635d-4805-87b3-54af6cc3a436">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>81.955 66.84 11.92 81.955 61.41 11.92 83.91 60.0 9.09 83.91 68.25 9.09 81.955 66.84 11.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4bae73b0-6f8f-44ab-8a1b-cb53fe240d94">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>81.955 61.41 11.92 80.0 60.0 9.09 83.91 60.0 9.09 81.955 61.41 11.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="22ad0172-e999-4f71-8ad6-0b297a0ad7e0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>81.955 66.84 11.92 83.91 68.25 9.09 80.0 68.25 9.09 81.955 66.84 11.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1c70d09d-2183-45bd-9d6c-cd4f559130da">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 60.0 0.0 83.91 60.0 0.0 83.91 60.0 9.09 80.0 60.0 9.09 80.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="78f2f48d-d2cb-41a1-8ff3-1de3ee3806b7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.91 60.0 0.0 83.91 68.25 0.0 83.91 68.25 9.09 83.91 60.0 9.09 83.91 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="54b28a80-cd55-4f8b-aa3b-d03d2e78d42f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.91 68.25 0.0 80.0 68.25 0.0 80.0 68.25 9.09 83.91 68.25 9.09 83.91 68.25 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod2MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4149558f-0289-4450-85ea-6e65f08df3a4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 68.25 0.0 80.0 60.0 0.0 80.0 60.0 9.09 80.0 68.25 9.09 80.0 68.25 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
