<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns="http://www.opengis.net/citygml/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:fme="http://www.safe.com/xml/xmltables">
  <gml:name>LOD2_2_F0</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="9fd16237-61d1-494c-b265-4e51b42046ed">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1969</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2229e6bf-31d8-4e2a-b77b-054a2e0df3f0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 0.0 0.0 0.0 7.77 0.0 3.34 7.77 0.0 3.34 0.0 0.0 0.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4edb2b16-474f-4051-81cc-b558a3792642">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 0.0 17.45 3.34 0.0 17.45 3.34 7.77 17.45 0.0 7.77 17.45 0.0 0.0 17.45</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fda31be2-7bfc-415b-8ef7-3fd5268e23d9">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 0.0 0.0 3.34 0.0 0.0 3.34 0.0 17.45 0.0 0.0 17.45 0.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1e48b3b6-5203-403d-a4ca-87b7734815bc">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>3.34 0.0 0.0 3.34 7.77 0.0 3.34 7.77 17.45 3.34 0.0 17.45 3.34 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a37ae920-0c72-467f-bb30-51dd7941563a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>3.34 7.77 0.0 0.0 7.77 0.0 0.0 7.77 17.45 3.34 7.77 17.45 3.34 7.77 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ce79bbcd-4563-42b8-9f64-7afa13b97549">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 7.77 0.0 0.0 0.0 0.0 0.0 0.0 17.45 0.0 7.77 17.45 0.0 7.77 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6e58349d-cbc4-4c44-95e6-5e550d5d0899">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a4f87e8f-be2e-4ee5-91bd-477b9bc00d79">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 20.0 0.0 0.0 29.6 0.0 5.72 29.6 0.0 5.72 20.0 0.0 0.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5aa6f3a4-804d-47ca-b3b3-0b6044d1c535">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 29.6 6.07 0.0 20.0 6.07 5.72 20.0 3.27 5.72 29.6 3.27 0.0 29.6 6.07</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="62c54f62-d880-4908-8bae-7112764ce8de">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 20.0 6.07 0.0 20.0 0.0 5.72 20.0 0.0 5.72 20.0 3.27 0.0 20.0 6.07</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6b311d53-47c9-44c1-bc39-a4971cfe2406">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>5.72 20.0 0.0 5.72 29.6 0.0 5.72 29.6 3.27 5.72 20.0 3.27 5.72 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="555d3bb2-5c8d-44bc-aa52-ea7722049415">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>5.72 29.6 3.27 5.72 29.6 0.0 0.0 29.6 0.0 0.0 29.6 6.07 5.72 29.6 3.27</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d796b01d-3719-47b0-aa0a-2acbcd542477">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 29.6 6.07 0.0 29.6 0.0 0.0 20.0 0.0 0.0 20.0 6.07 0.0 29.6 6.07</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="92a9ffcc-a809-436b-ab8f-213341025556">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1965</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4b94cd16-e1f9-4fc5-aed5-af212b5dbc20">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 40.0 0.0 0.0 43.04 0.0 7.38 43.04 0.0 7.38 40.0 0.0 0.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d3001002-b451-4224-9b7b-7aa6ce742bda">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 40.0 16.1 7.38 40.0 16.1 7.38 43.04 16.1 0.0 43.04 16.1 0.0 40.0 16.1</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fb63938d-e24c-4b7b-9f91-38912e8c2401">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 40.0 0.0 7.38 40.0 0.0 7.38 40.0 16.1 0.0 40.0 16.1 0.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ab6771c5-8c7f-4b08-b393-de8c575bf07e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>7.38 40.0 0.0 7.38 43.04 0.0 7.38 43.04 16.1 7.38 40.0 16.1 7.38 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1cf023c3-3210-4af0-9591-011bda2e626b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>7.38 43.04 0.0 0.0 43.04 0.0 0.0 43.04 16.1 7.38 43.04 16.1 7.38 43.04 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7e8a6d75-3077-4cd8-be27-bbc8919a9cb8">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 43.04 0.0 0.0 40.0 0.0 0.0 40.0 16.1 0.0 43.04 16.1 0.0 43.04 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="580bc1f5-b498-4048-a45b-e65a9d18c75a">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1990</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="84c4ad6c-47f3-449a-a2c2-a02564c17d61">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 60.0 0.0 0.0 63.37 0.0 9.27 63.37 0.0 9.27 60.0 0.0 0.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2edaa1f2-97b6-40ba-b8b5-4a189d4804a3">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 63.37 8.66 0.0 60.0 8.66 9.27 60.0 6.18 9.27 63.37 6.18 0.0 63.37 8.66</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="14e555ee-a4de-4ce5-9a85-fd5eb7c088dd">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 60.0 8.66 0.0 60.0 0.0 9.27 60.0 0.0 9.27 60.0 6.18 0.0 60.0 8.66</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6b7bc135-9d4e-4c50-8330-777066829854">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>9.27 60.0 0.0 9.27 63.37 0.0 9.27 63.37 6.18 9.27 60.0 6.18 9.27 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7438784c-5649-4aeb-9efc-5e7b600b4617">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>9.27 63.37 6.18 9.27 63.37 0.0 0.0 63.37 0.0 0.0 63.37 8.66 9.27 63.37 6.18</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="36545a68-3d66-4e00-8c83-0160885ec076">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>0.0 63.37 8.66 0.0 63.37 0.0 0.0 60.0 0.0 0.0 60.0 8.66 0.0 63.37 8.66</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="95a4abfb-cd95-422f-9c27-ebea911dcc4f">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1967</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="59f09cfc-0637-4c67-9649-b9dae463a3d9">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 0.0 0.0 20.0 5.74 0.0 23.990000000000002 5.74 0.0 23.990000000000002 0.0 0.0 20.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="08195c46-e62b-4a69-a563-07c90d84caf6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.995 2.09 11.379999999999999 21.995 3.6500000000000004 11.379999999999999 20.0 5.74 9.33 20.0 0.0 9.33 21.995 2.09 11.379999999999999</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9c94b535-ef05-4d49-9013-97e835859b79">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.995 3.6500000000000004 11.379999999999999 21.995 2.09 11.379999999999999 23.990000000000002 0.0 9.33 23.990000000000002 5.74 9.33 21.995 3.6500000000000004 11.379999999999999</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d2c80185-448b-4e42-91f7-eed78f596330">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.995 2.09 11.379999999999999 20.0 0.0 9.33 23.990000000000002 0.0 9.33 21.995 2.09 11.379999999999999</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="30f37269-ca5e-4aa4-9212-2d5b917ad4ff">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.995 3.6500000000000004 11.379999999999999 23.990000000000002 5.74 9.33 20.0 5.74 9.33 21.995 3.6500000000000004 11.379999999999999</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ab8dda8d-51c8-477b-9e66-91bc6feda5bb">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 0.0 0.0 23.990000000000002 0.0 0.0 23.990000000000002 0.0 9.33 20.0 0.0 9.33 20.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="51c35564-9a09-4278-a328-cf6c4b5b793d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.990000000000002 0.0 0.0 23.990000000000002 5.74 0.0 23.990000000000002 5.74 9.33 23.990000000000002 0.0 9.33 23.990000000000002 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="52483e92-e8b6-46ed-867e-432b028ab99d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.990000000000002 5.74 0.0 20.0 5.74 0.0 20.0 5.74 9.33 23.990000000000002 5.74 9.33 23.990000000000002 5.74 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0c606174-f8e0-41cd-868a-bfbfa3f5a13a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 5.74 0.0 20.0 0.0 0.0 20.0 0.0 9.33 20.0 5.74 9.33 20.0 5.74 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="3d5dea93-0b71-41ff-b5f5-438bad25f186">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1959</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2dea5374-ecfa-4e5f-875e-1194527ebf3b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 20.0 0.0 20.0 28.83 0.0 23.11 28.83 0.0 23.11 20.0 0.0 20.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="267590c9-cae4-491a-8d73-a26550a0b9e7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.555 21.57 11.72 21.555 27.259999999999998 11.72 20.0 28.83 9.39 20.0 20.0 9.39 21.555 21.57 11.72</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4abb423f-3d1b-4682-84af-4af0d44c5172">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.555 27.259999999999998 11.72 21.555 21.57 11.72 23.11 20.0 9.39 23.11 28.83 9.39 21.555 27.259999999999998 11.72</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="65829fd0-4181-4c22-b880-af1096d7df6a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.555 21.57 11.72 20.0 20.0 9.39 23.11 20.0 9.39 21.555 21.57 11.72</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="dbd8d9e5-2047-444f-90be-17a9a6404d96">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>21.555 27.259999999999998 11.72 23.11 28.83 9.39 20.0 28.83 9.39 21.555 27.259999999999998 11.72</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1238fc3d-a5e8-4e0a-af98-64c3c2867704">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 20.0 0.0 23.11 20.0 0.0 23.11 20.0 9.39 20.0 20.0 9.39 20.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c32bc649-c6be-45b3-af90-54a352071c69">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.11 20.0 0.0 23.11 28.83 0.0 23.11 28.83 9.39 23.11 20.0 9.39 23.11 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0411e095-f96a-443e-9fa2-844e402d011f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.11 28.83 0.0 20.0 28.83 0.0 20.0 28.83 9.39 23.11 28.83 9.39 23.11 28.83 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="fd959bf9-2b38-4e51-afe9-0432caf24ebf">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 28.83 0.0 20.0 20.0 0.0 20.0 20.0 9.39 20.0 28.83 9.39 20.0 28.83 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="60bc0619-7b36-44bd-ae91-da3c4563c587">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1948</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f670058d-4c46-4290-b30f-fda8be186000">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 40.0 0.0 20.0 48.730000000000004 0.0 23.16 48.730000000000004 0.0 23.16 40.0 0.0 20.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6d6f4e7a-a0f4-472a-95b1-dce0351672c0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 48.730000000000004 11.940000000000001 20.0 40.0 11.940000000000001 23.16 40.0 9.9 23.16 48.730000000000004 9.9 20.0 48.730000000000004 11.940000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="45f47619-86cc-420e-a245-fb080fb8dd1d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 40.0 11.940000000000001 20.0 40.0 0.0 23.16 40.0 0.0 23.16 40.0 9.9 20.0 40.0 11.940000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b74ef424-cab9-4f8b-93e1-eb0d204a9eb9">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.16 40.0 0.0 23.16 48.730000000000004 0.0 23.16 48.730000000000004 9.9 23.16 40.0 9.9 23.16 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3a145e69-63c9-41f9-9125-4fe1dc131c1d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>23.16 48.730000000000004 9.9 23.16 48.730000000000004 0.0 20.0 48.730000000000004 0.0 20.0 48.730000000000004 11.940000000000001 23.16 48.730000000000004 9.9</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0b7e12ec-4af9-4089-9072-f7f6ae8c1c87">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 48.730000000000004 11.940000000000001 20.0 48.730000000000004 0.0 20.0 40.0 0.0 20.0 40.0 11.940000000000001 20.0 48.730000000000004 11.940000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="d333dfad-c0a0-4cad-8565-a93c5e17ce8d">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>2009</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6307e470-b443-4b06-90b4-8c81a1fcc5c4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 60.0 0.0 20.0 64.12 0.0 28.36 64.12 0.0 28.36 60.0 0.0 20.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2e82419b-531a-4d6b-9b55-a9488e8faa45">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 60.0 6.8 28.36 60.0 6.8 28.36 64.12 6.8 20.0 64.12 6.8 20.0 60.0 6.8</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="327dcdf1-a4fc-468d-976a-2046968b4153">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 60.0 0.0 28.36 60.0 0.0 28.36 60.0 6.8 20.0 60.0 6.8 20.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c2ed4da7-e577-412f-b653-7feccff43e2f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>28.36 60.0 0.0 28.36 64.12 0.0 28.36 64.12 6.8 28.36 60.0 6.8 28.36 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c13811cd-a0c5-4f8e-8f02-b57b3f3caa27">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>28.36 64.12 0.0 20.0 64.12 0.0 20.0 64.12 6.8 28.36 64.12 6.8 28.36 64.12 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="51fa45a7-873f-4045-a972-f44fcf21d0d5">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>20.0 64.12 0.0 20.0 60.0 0.0 20.0 60.0 6.8 20.0 64.12 6.8 20.0 64.12 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="fcbb6855-ac3c-4a96-97b2-4a33bbfeede9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="591490bf-8fd9-4a7c-9714-1191f479c285">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 0.0 0.0 40.0 7.35 0.0 46.08 7.35 0.0 46.08 0.0 0.0 40.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5753cf2c-27fc-4dee-a2b3-7a76881e9e09">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>43.04 0.0 13.620000000000001 43.04 7.35 13.620000000000001 40.0 7.35 10.08 40.0 0.0 10.08 43.04 0.0 13.620000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b41727ea-0b6f-4a01-b795-1b43056609e5">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>43.04 7.35 13.620000000000001 43.04 0.0 13.620000000000001 46.08 0.0 10.08 46.08 7.35 10.08 43.04 7.35 13.620000000000001</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="752def0d-87b8-427b-9444-cc5f760512e7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 0.0 10.08 40.0 0.0 0.0 46.08 0.0 0.0 46.08 0.0 10.08 43.04 0.0 13.620000000000001 40.0 0.0 10.08</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6c547771-a702-4028-af18-0bb7cadab191">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.08 0.0 0.0 46.08 7.35 0.0 46.08 7.35 10.08 46.08 0.0 10.08 46.08 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1759f40e-4caa-4605-8f92-7dc78b3c56e6">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.08 7.35 10.08 46.08 7.35 0.0 40.0 7.35 0.0 40.0 7.35 10.08 43.04 7.35 13.620000000000001 46.08 7.35 10.08</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="557f8877-13f4-4e49-a5af-c75caea465fc">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 7.35 10.08 40.0 7.35 0.0 40.0 0.0 0.0 40.0 0.0 10.08 40.0 7.35 10.08</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="ba98e18f-aa5d-4a9d-8aaf-3f21da173020">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1947</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="546b650a-f5e3-4608-be66-8432de296f45">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 20.0 0.0 40.0 29.14 0.0 46.730000000000004 29.14 0.0 46.730000000000004 20.0 0.0 40.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="39c8ab3a-c6bb-49e6-b036-4c77400e69ed">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 20.0 6.7 46.730000000000004 20.0 6.7 46.730000000000004 29.14 6.7 40.0 29.14 6.7 40.0 20.0 6.7</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f1893b2d-83b4-4bfd-8010-3c9b4da01fe5">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 20.0 0.0 46.730000000000004 20.0 0.0 46.730000000000004 20.0 6.7 40.0 20.0 6.7 40.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="bc5fe7b4-7142-4a05-a529-bcc40583dfd4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.730000000000004 20.0 0.0 46.730000000000004 29.14 0.0 46.730000000000004 29.14 6.7 46.730000000000004 20.0 6.7 46.730000000000004 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="89cbdd1f-8c5b-4cbb-a03c-edb9777ce406">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>46.730000000000004 29.14 0.0 40.0 29.14 0.0 40.0 29.14 6.7 46.730000000000004 29.14 6.7 46.730000000000004 29.14 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="337765de-f18a-4e63-b67c-4f4f16cca7f7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 29.14 0.0 40.0 20.0 0.0 40.0 20.0 6.7 40.0 29.14 6.7 40.0 29.14 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="b6d27324-c418-4f19-9c31-45eebddc6300">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1982</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="587a495b-d7f7-461c-89c5-c3119719c583">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 40.0 0.0 40.0 45.5 0.0 47.44 45.5 0.0 47.44 40.0 0.0 40.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4f5c7f34-ca76-4310-84dd-6f598cd214b2">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 40.0 13.36 47.44 40.0 13.36 47.44 45.5 13.36 40.0 45.5 13.36 40.0 40.0 13.36</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4a3be02a-b3d5-40bf-b2c6-ac7b4d179c71">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 40.0 0.0 47.44 40.0 0.0 47.44 40.0 13.36 40.0 40.0 13.36 40.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f35b36f0-c29b-40e8-944f-c70824beb002">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>47.44 40.0 0.0 47.44 45.5 0.0 47.44 45.5 13.36 47.44 40.0 13.36 47.44 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3bd7008b-24f2-4d95-b885-e62a5c44eccd">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>47.44 45.5 0.0 40.0 45.5 0.0 40.0 45.5 13.36 47.44 45.5 13.36 47.44 45.5 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2188b73a-6cc5-4905-b55d-d5a5c6cb4e3a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 45.5 0.0 40.0 40.0 0.0 40.0 40.0 13.36 40.0 45.5 13.36 40.0 45.5 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45162044-732c-4d1b-9ee7-877f1376456e">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1989</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="6069eb96-8be4-43fb-a842-f143b181971d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 60.0 0.0 40.0 67.81 0.0 43.07 67.81 0.0 43.07 60.0 0.0 40.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="24b9398e-450c-4490-a19e-26f685e21298">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 60.0 12.4 43.07 60.0 12.4 43.07 67.81 12.4 40.0 67.81 12.4 40.0 60.0 12.4</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7098244f-6ced-49f3-8b84-39d0dbfc9290">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 60.0 0.0 43.07 60.0 0.0 43.07 60.0 12.4 40.0 60.0 12.4 40.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="90efaa2e-5457-4aa8-bcac-ef98bdddb06b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>43.07 60.0 0.0 43.07 67.81 0.0 43.07 67.81 12.4 43.07 60.0 12.4 43.07 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9b4628e0-1fcf-43d0-8944-5ed7fcdb553d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>43.07 67.81 0.0 40.0 67.81 0.0 40.0 67.81 12.4 43.07 67.81 12.4 43.07 67.81 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4d5ec46e-a38e-4ae3-a18a-5a57e8788544">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>40.0 67.81 0.0 40.0 60.0 0.0 40.0 60.0 12.4 40.0 67.81 12.4 40.0 67.81 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="6eb5dd57-e0d2-4de1-8989-e3622fde68f0">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1976</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e75c3496-94f7-4155-aded-6a1749254c2d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 0.0 0.0 60.0 5.06 0.0 69.18 5.06 0.0 69.18 0.0 0.0 60.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1ef91d21-5c05-4834-ac61-84fb24ce6e9a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 5.06 5.92 60.0 0.0 5.92 69.18 0.0 3.12 69.18 5.06 3.12 60.0 5.06 5.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c681bb3d-bc7d-47ce-a0f7-91ad5828f118">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 0.0 5.92 60.0 0.0 0.0 69.18 0.0 0.0 69.18 0.0 3.12 60.0 0.0 5.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="dda4e536-2b6a-4eee-add2-d9164957fb3a">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>69.18 0.0 0.0 69.18 5.06 0.0 69.18 5.06 3.12 69.18 0.0 3.12 69.18 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2a0ef546-47c8-42af-bc9b-acb9b91d0fb7">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>69.18 5.06 3.12 69.18 5.06 0.0 60.0 5.06 0.0 60.0 5.06 5.92 69.18 5.06 3.12</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4913abb5-fcb2-4628-8ac4-5e54feed9d58">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 5.06 5.92 60.0 5.06 0.0 60.0 0.0 0.0 60.0 0.0 5.92 60.0 5.06 5.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45d9f60d-0834-41d0-9844-5b92fb1b72a9">
      <bldg:roofType>Gabled</bldg:roofType>
      <bldg:yearOfConstruction>1974</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="90547e46-22cb-4ae3-94cc-012516291f50">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 20.0 0.0 60.0 27.17 0.0 63.38 27.17 0.0 63.38 20.0 0.0 60.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a7f62a5b-1180-4e06-8dba-ae07c21a02c1">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>61.69 20.0 6.29 61.69 27.17 6.29 60.0 27.17 3.49 60.0 20.0 3.49 61.69 20.0 6.29</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0033c497-0e1d-4d66-b620-9052a3e8066d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>61.69 27.17 6.29 61.69 20.0 6.29 63.38 20.0 3.49 63.38 27.17 3.49 61.69 27.17 6.29</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="d6633b04-0a69-4a5f-a779-3d2e105a91e8">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 20.0 3.49 60.0 20.0 0.0 63.38 20.0 0.0 63.38 20.0 3.49 61.69 20.0 6.29 60.0 20.0 3.49</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="90982105-75c6-41ff-9a1d-71de06a04376">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.38 20.0 0.0 63.38 27.17 0.0 63.38 27.17 3.49 63.38 20.0 3.49 63.38 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="cc9c6e05-59de-4171-999a-e4f02616374c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.38 27.17 3.49 63.38 27.17 0.0 60.0 27.17 0.0 60.0 27.17 3.49 61.69 27.17 6.29 63.38 27.17 3.49</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="327d084c-83f7-472f-97f2-4870fdb9d22e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 27.17 3.49 60.0 27.17 0.0 60.0 20.0 0.0 60.0 20.0 3.49 60.0 27.17 3.49</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="555175a2-22c2-41a7-b85f-2fb869fc519b">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1972</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e427f3b8-6e7e-40be-a3aa-9704ff236abf">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 40.0 0.0 60.0 45.29 0.0 63.05 45.29 0.0 63.05 40.0 0.0 60.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="241db883-3f7e-4a74-9c0a-613392d4ad1f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 45.29 5.82 60.0 40.0 5.82 63.05 40.0 3.02 63.05 45.29 3.02 60.0 45.29 5.82</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a903b76e-e738-4511-bbb9-4f482ffd3dea">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 40.0 5.82 60.0 40.0 0.0 63.05 40.0 0.0 63.05 40.0 3.02 60.0 40.0 5.82</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3daaa8eb-733d-49b7-a180-23126f6bfa19">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.05 40.0 0.0 63.05 45.29 0.0 63.05 45.29 3.02 63.05 40.0 3.02 63.05 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="27be64ee-41fa-44e5-a699-8b4f6e0a5b44">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.05 45.29 3.02 63.05 45.29 0.0 60.0 45.29 0.0 60.0 45.29 5.82 63.05 45.29 3.02</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c198dc53-1a33-4d4d-968a-5b9d115a67b5">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 45.29 5.82 60.0 45.29 0.0 60.0 40.0 0.0 60.0 40.0 5.82 60.0 45.29 5.82</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="32ef008b-6848-4e06-ad57-2cec22eeb093">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="64fd147a-8c25-4f43-a9f9-80a0a39da88b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 60.0 0.0 60.0 63.72 0.0 63.76 63.72 0.0 63.76 60.0 0.0 60.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7081a716-a448-430b-97db-70e428f2651b">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 60.0 13.6 63.76 60.0 13.6 63.76 63.72 13.6 60.0 63.72 13.6 60.0 60.0 13.6</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="06597823-b913-4b3a-882b-6c9853a05a8c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 60.0 0.0 63.76 60.0 0.0 63.76 60.0 13.6 60.0 60.0 13.6 60.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="81d5cdf4-937d-472c-81a5-9fe1ddb5ffaa">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.76 60.0 0.0 63.76 63.72 0.0 63.76 63.72 13.6 63.76 60.0 13.6 63.76 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="63af2735-c435-49b2-a170-98a9e23230b8">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>63.76 63.72 0.0 60.0 63.72 0.0 60.0 63.72 13.6 63.76 63.72 13.6 63.76 63.72 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0770e3c3-b6ca-47ed-89e0-cdc4bd449e47">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>60.0 63.72 0.0 60.0 60.0 0.0 60.0 60.0 13.6 60.0 63.72 13.6 60.0 63.72 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="a64f3754-2a76-4790-ad49-598f014e6814">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="000b3abc-e0ba-47fe-aee2-55a3f82b4da0">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 0.0 0.0 80.0 9.8 0.0 84.39 9.8 0.0 84.39 0.0 0.0 80.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f8090e59-44ea-4aa1-a161-3675e38b0ccd">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 0.0 14.0 84.39 0.0 14.0 84.39 9.8 14.0 80.0 9.8 14.0 80.0 0.0 14.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1f57dfee-b9f7-43ba-95b8-16d783d14e4c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 0.0 0.0 84.39 0.0 0.0 84.39 0.0 14.0 80.0 0.0 14.0 80.0 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="3b4449cc-7d1c-42ac-8faf-d9b6d53b74ac">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>84.39 0.0 0.0 84.39 9.8 0.0 84.39 9.8 14.0 84.39 0.0 14.0 84.39 0.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="51fb2c14-8a68-4eb2-91a5-1305d69fd8af">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>84.39 9.8 0.0 80.0 9.8 0.0 80.0 9.8 14.0 84.39 9.8 14.0 84.39 9.8 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a5a49c92-56df-4bfe-8404-8b1484cf6507">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 9.8 0.0 80.0 0.0 0.0 80.0 0.0 14.0 80.0 9.8 14.0 80.0 9.8 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="4e73a2b8-54cc-4722-a8b8-57971461b270">
      <bldg:roofType>Shed</bldg:roofType>
      <bldg:yearOfConstruction>1952</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a594d08d-cffa-40b2-83d8-9566d55e6d6d">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 20.0 0.0 80.0 24.13 0.0 85.27 24.13 0.0 85.27 20.0 0.0 80.0 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="4c1a0451-ddf0-43cc-8871-ec875c81697e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 24.13 9.39 80.0 20.0 9.39 85.27 20.0 6.92 85.27 24.13 6.92 80.0 24.13 9.39</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="9dcc506a-6710-4077-8b8a-490aa47ebb38">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 20.0 9.39 80.0 20.0 0.0 85.27 20.0 0.0 85.27 20.0 6.92 80.0 20.0 9.39</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b41483da-cf91-47db-9d26-ebb9264c9170">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>85.27 20.0 0.0 85.27 24.13 0.0 85.27 24.13 6.92 85.27 20.0 6.92 85.27 20.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="db7cfe5b-2b3b-4dc2-81ea-118ce8bbd169">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>85.27 24.13 6.92 85.27 24.13 0.0 80.0 24.13 0.0 80.0 24.13 9.39 85.27 24.13 6.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="823c7422-c7fe-4010-8c51-c496a2f50016">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 24.13 9.39 80.0 24.13 0.0 80.0 20.0 0.0 80.0 20.0 9.39 80.0 24.13 9.39</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="44e2c197-1881-4ec3-bc14-f284bfa8716c">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1966</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="ef1dd909-3a29-49ac-810b-41a91e1deda4">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 40.0 0.0 80.0 49.62 0.0 83.52 49.62 0.0 83.52 40.0 0.0 80.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="332dc439-05d5-4498-8edc-3b0a9563f419">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 40.0 15.5 83.52 40.0 15.5 83.52 49.62 15.5 80.0 49.62 15.5 80.0 40.0 15.5</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="f7f9aefe-0338-42a2-b25b-3eeb7c995a6f">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 40.0 0.0 83.52 40.0 0.0 83.52 40.0 15.5 80.0 40.0 15.5 80.0 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="513465df-9905-4b84-941d-7df53a1cfd48">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.52 40.0 0.0 83.52 49.62 0.0 83.52 49.62 15.5 83.52 40.0 15.5 83.52 40.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="7a8ca1cb-437e-4db5-9ff1-e9d8a856958e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.52 49.62 0.0 80.0 49.62 0.0 80.0 49.62 15.5 83.52 49.62 15.5 83.52 49.62 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="0d6b7d3c-cd81-426c-9e25-3244797c13f3">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 49.62 0.0 80.0 40.0 0.0 80.0 40.0 15.5 80.0 49.62 15.5 80.0 49.62 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="708daa94-e4a5-413b-8efb-3d9bc59e9f58">
      <bldg:roofType>Hipped</bldg:roofType>
      <bldg:yearOfConstruction>1998</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:boundedBy>
        <bldg:GroundSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="2da5ff38-fed2-4eb8-b814-7910f258202e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 60.0 0.0 80.0 68.25 0.0 83.91 68.25 0.0 83.91 60.0 0.0 80.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="e8b5bf38-f4d7-44bf-81b7-407249e3cfba">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>81.955 61.41 11.92 81.955 66.84 11.92 80.0 68.25 9.09 80.0 60.0 9.09 81.955 61.41 11.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="5439de5e-472f-4794-96b3-b4091df60517">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>81.955 66.84 11.92 81.955 61.41 11.92 83.91 60.0 9.09 83.91 68.25 9.09 81.955 66.84 11.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="618ffc12-a74c-4abd-9818-96ce50b2fc4e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>81.955 61.41 11.92 80.0 60.0 9.09 83.91 60.0 9.09 81.955 61.41 11.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="1850c212-f1ca-4c7e-a439-543f89d1f87e">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>81.955 66.84 11.92 83.91 68.25 9.09 80.0 68.25 9.09 81.955 66.84 11.92</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="c2b3cfcd-d327-42f2-8621-3e8fe7993d0c">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 60.0 0.0 83.91 60.0 0.0 83.91 60.0 9.09 80.0 60.0 9.09 80.0 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="979e4e96-7d61-4879-a310-115f016b5404">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.91 60.0 0.0 83.91 68.25 0.0 83.91 68.25 9.09 83.91 60.0 9.09 83.91 60.0 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="a42423a7-34ff-4720-b68c-c4fde2912eb9">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>83.91 68.25 0.0 80.0 68.25 0.0 80.0 68.25 9.09 83.91 68.25 9.09 83.91 68.25 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface>
          <bldg:lod3MultiSurface>
            <gml:MultiSurface>
              <gml:surfaceMember>
                <gml:Polygon gml:id="b2b63560-7692-4c97-80af-36b2304c1529">
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList>80.0 68.25 0.0 80.0 60.0 0.0 80.0 60.0 9.09 80.0 68.25 9.09 80.0 68.25 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod3MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
